/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1HealthGet200Response
 */
export interface ApiV1HealthGet200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV1HealthGet200Response
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiV1HealthGet200Response
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof ApiV1HealthGet200Response
     */
    environment?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1HealthGet200Response
     */
    version?: string;
}

/**
 * Check if a given object implements the ApiV1HealthGet200Response interface.
 */
export function instanceOfApiV1HealthGet200Response(value: object): value is ApiV1HealthGet200Response {
    return true;
}

export function ApiV1HealthGet200ResponseFromJSON(json: any): ApiV1HealthGet200Response {
    return ApiV1HealthGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1HealthGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1HealthGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'environment': json['environment'] == null ? undefined : json['environment'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function ApiV1HealthGet200ResponseToJSON(json: any): ApiV1HealthGet200Response {
    return ApiV1HealthGet200ResponseToJSONTyped(json, false);
}

export function ApiV1HealthGet200ResponseToJSONTyped(value?: ApiV1HealthGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'environment': value['environment'],
        'version': value['version'],
    };
}

