/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1AuthAdminUsersPostRequest
 */
export interface ApiV1AuthAdminUsersPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthAdminUsersPostRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthAdminUsersPostRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthAdminUsersPostRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthAdminUsersPostRequest
     */
    lastName: string;
    /**
     * 
     * @type {ApiV1AuthAdminUsersPostRequestRoleEnum}
     * @memberof ApiV1AuthAdminUsersPostRequest
     */
    role: ApiV1AuthAdminUsersPostRequestRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthAdminUsersPostRequest
     */
    phone?: string;
}


/**
 * @export
 */
export const ApiV1AuthAdminUsersPostRequestRoleEnum = {
    SuperAdmin: 'super_admin',
    HeadCoach: 'head_coach',
    AssistantCoach: 'assistant_coach'
} as const;
export type ApiV1AuthAdminUsersPostRequestRoleEnum = typeof ApiV1AuthAdminUsersPostRequestRoleEnum[keyof typeof ApiV1AuthAdminUsersPostRequestRoleEnum];


/**
 * Check if a given object implements the ApiV1AuthAdminUsersPostRequest interface.
 */
export function instanceOfApiV1AuthAdminUsersPostRequest(value: object): value is ApiV1AuthAdminUsersPostRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function ApiV1AuthAdminUsersPostRequestFromJSON(json: any): ApiV1AuthAdminUsersPostRequest {
    return ApiV1AuthAdminUsersPostRequestFromJSONTyped(json, false);
}

export function ApiV1AuthAdminUsersPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AuthAdminUsersPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'role': json['role'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function ApiV1AuthAdminUsersPostRequestToJSON(json: any): ApiV1AuthAdminUsersPostRequest {
    return ApiV1AuthAdminUsersPostRequestToJSONTyped(json, false);
}

export function ApiV1AuthAdminUsersPostRequestToJSONTyped(value?: ApiV1AuthAdminUsersPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'role': value['role'],
        'phone': value['phone'],
    };
}

