/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1SchedulesIdSectionsPostRequest
 */
export interface ApiV1SchedulesIdSectionsPostRequest {
    /**
     * 
     * @type {ApiV1SchedulesIdSectionsPostRequestTypeEnum}
     * @memberof ApiV1SchedulesIdSectionsPostRequest
     */
    type: ApiV1SchedulesIdSectionsPostRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiV1SchedulesIdSectionsPostRequest
     */
    title: string;
}


/**
 * @export
 */
export const ApiV1SchedulesIdSectionsPostRequestTypeEnum = {
    General: 'general',
    PositionPlayers: 'position_players',
    Pitchers: 'pitchers',
    GrinderPerformance: 'grinder_performance',
    GrinderHitting: 'grinder_hitting',
    GrinderDefensive: 'grinder_defensive',
    Bullpen: 'bullpen',
    LiveBp: 'live_bp'
} as const;
export type ApiV1SchedulesIdSectionsPostRequestTypeEnum = typeof ApiV1SchedulesIdSectionsPostRequestTypeEnum[keyof typeof ApiV1SchedulesIdSectionsPostRequestTypeEnum];


/**
 * Check if a given object implements the ApiV1SchedulesIdSectionsPostRequest interface.
 */
export function instanceOfApiV1SchedulesIdSectionsPostRequest(value: object): value is ApiV1SchedulesIdSectionsPostRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ApiV1SchedulesIdSectionsPostRequestFromJSON(json: any): ApiV1SchedulesIdSectionsPostRequest {
    return ApiV1SchedulesIdSectionsPostRequestFromJSONTyped(json, false);
}

export function ApiV1SchedulesIdSectionsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SchedulesIdSectionsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'title': json['title'],
    };
}

export function ApiV1SchedulesIdSectionsPostRequestToJSON(json: any): ApiV1SchedulesIdSectionsPostRequest {
    return ApiV1SchedulesIdSectionsPostRequestToJSONTyped(json, false);
}

export function ApiV1SchedulesIdSectionsPostRequestToJSONTyped(value?: ApiV1SchedulesIdSectionsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'title': value['title'],
    };
}

