/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1TeamsPostRequest
 */
export interface ApiV1TeamsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsPostRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsPostRequest
     */
    programName?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsPostRequest
     */
    conference?: string;
    /**
     * 
     * @type {ApiV1TeamsPostRequestDivisionEnum}
     * @memberof ApiV1TeamsPostRequest
     */
    division?: ApiV1TeamsPostRequestDivisionEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsPostRequest
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsPostRequest
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsPostRequest
     */
    primaryColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsPostRequest
     */
    secondaryColor?: string;
}


/**
 * @export
 */
export const ApiV1TeamsPostRequestDivisionEnum = {
    D1: 'D1',
    D2: 'D2',
    D3: 'D3',
    Naia: 'NAIA',
    Juco: 'JUCO'
} as const;
export type ApiV1TeamsPostRequestDivisionEnum = typeof ApiV1TeamsPostRequestDivisionEnum[keyof typeof ApiV1TeamsPostRequestDivisionEnum];


/**
 * Check if a given object implements the ApiV1TeamsPostRequest interface.
 */
export function instanceOfApiV1TeamsPostRequest(value: object): value is ApiV1TeamsPostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ApiV1TeamsPostRequestFromJSON(json: any): ApiV1TeamsPostRequest {
    return ApiV1TeamsPostRequestFromJSONTyped(json, false);
}

export function ApiV1TeamsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1TeamsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'programName': json['program_name'] == null ? undefined : json['program_name'],
        'conference': json['conference'] == null ? undefined : json['conference'],
        'division': json['division'] == null ? undefined : json['division'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'primaryColor': json['primary_color'] == null ? undefined : json['primary_color'],
        'secondaryColor': json['secondary_color'] == null ? undefined : json['secondary_color'],
    };
}

export function ApiV1TeamsPostRequestToJSON(json: any): ApiV1TeamsPostRequest {
    return ApiV1TeamsPostRequestToJSONTyped(json, false);
}

export function ApiV1TeamsPostRequestToJSONTyped(value?: ApiV1TeamsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'program_name': value['programName'],
        'conference': value['conference'],
        'division': value['division'],
        'city': value['city'],
        'state': value['state'],
        'primary_color': value['primaryColor'],
        'secondary_color': value['secondaryColor'],
    };
}

