/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1IntegrationsPrestoConfigurePostRequest
 */
export interface ApiV1IntegrationsPrestoConfigurePostRequest {
    /**
     * 
     * @type {object}
     * @memberof ApiV1IntegrationsPrestoConfigurePostRequest
     */
    credentials?: object;
}

/**
 * Check if a given object implements the ApiV1IntegrationsPrestoConfigurePostRequest interface.
 */
export function instanceOfApiV1IntegrationsPrestoConfigurePostRequest(value: object): value is ApiV1IntegrationsPrestoConfigurePostRequest {
    return true;
}

export function ApiV1IntegrationsPrestoConfigurePostRequestFromJSON(json: any): ApiV1IntegrationsPrestoConfigurePostRequest {
    return ApiV1IntegrationsPrestoConfigurePostRequestFromJSONTyped(json, false);
}

export function ApiV1IntegrationsPrestoConfigurePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1IntegrationsPrestoConfigurePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'credentials': json['credentials'] == null ? undefined : json['credentials'],
    };
}

export function ApiV1IntegrationsPrestoConfigurePostRequestToJSON(json: any): ApiV1IntegrationsPrestoConfigurePostRequest {
    return ApiV1IntegrationsPrestoConfigurePostRequestToJSONTyped(json, false);
}

export function ApiV1IntegrationsPrestoConfigurePostRequestToJSONTyped(value?: ApiV1IntegrationsPrestoConfigurePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credentials': value['credentials'],
    };
}

