/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ReportsByIdIdPutRequest
 */
export interface ApiV1ReportsByIdIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ReportsByIdIdPutRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ReportsByIdIdPutRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ReportsByIdIdPutRequest
     */
    status?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1ReportsByIdIdPutRequest
     */
    dataSources?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1ReportsByIdIdPutRequest
     */
    sections?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof ApiV1ReportsByIdIdPutRequest
     */
    filters?: object;
}

/**
 * Check if a given object implements the ApiV1ReportsByIdIdPutRequest interface.
 */
export function instanceOfApiV1ReportsByIdIdPutRequest(value: object): value is ApiV1ReportsByIdIdPutRequest {
    return true;
}

export function ApiV1ReportsByIdIdPutRequestFromJSON(json: any): ApiV1ReportsByIdIdPutRequest {
    return ApiV1ReportsByIdIdPutRequestFromJSONTyped(json, false);
}

export function ApiV1ReportsByIdIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ReportsByIdIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
        'dataSources': json['data_sources'] == null ? undefined : json['data_sources'],
        'sections': json['sections'] == null ? undefined : json['sections'],
        'filters': json['filters'] == null ? undefined : json['filters'],
    };
}

export function ApiV1ReportsByIdIdPutRequestToJSON(json: any): ApiV1ReportsByIdIdPutRequest {
    return ApiV1ReportsByIdIdPutRequestToJSONTyped(json, false);
}

export function ApiV1ReportsByIdIdPutRequestToJSONTyped(value?: ApiV1ReportsByIdIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'status': value['status'],
        'data_sources': value['dataSources'],
        'sections': value['sections'],
        'filters': value['filters'],
    };
}

