/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ReportsPostRequest
 */
export interface ApiV1ReportsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ReportsPostRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ReportsPostRequest
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ReportsPostRequest
     */
    description?: string;
    /**
     * 
     * @type {ApiV1ReportsPostRequestStatusEnum}
     * @memberof ApiV1ReportsPostRequest
     */
    status?: ApiV1ReportsPostRequestStatusEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1ReportsPostRequest
     */
    dataSources?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1ReportsPostRequest
     */
    sections?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof ApiV1ReportsPostRequest
     */
    filters?: object;
}


/**
 * @export
 */
export const ApiV1ReportsPostRequestStatusEnum = {
    Draft: 'draft',
    Published: 'published',
    Archived: 'archived'
} as const;
export type ApiV1ReportsPostRequestStatusEnum = typeof ApiV1ReportsPostRequestStatusEnum[keyof typeof ApiV1ReportsPostRequestStatusEnum];


/**
 * Check if a given object implements the ApiV1ReportsPostRequest interface.
 */
export function instanceOfApiV1ReportsPostRequest(value: object): value is ApiV1ReportsPostRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ApiV1ReportsPostRequestFromJSON(json: any): ApiV1ReportsPostRequest {
    return ApiV1ReportsPostRequestFromJSONTyped(json, false);
}

export function ApiV1ReportsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ReportsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'type': json['type'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
        'dataSources': json['data_sources'] == null ? undefined : json['data_sources'],
        'sections': json['sections'] == null ? undefined : json['sections'],
        'filters': json['filters'] == null ? undefined : json['filters'],
    };
}

export function ApiV1ReportsPostRequestToJSON(json: any): ApiV1ReportsPostRequest {
    return ApiV1ReportsPostRequestToJSONTyped(json, false);
}

export function ApiV1ReportsPostRequestToJSONTyped(value?: ApiV1ReportsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'type': value['type'],
        'description': value['description'],
        'status': value['status'],
        'data_sources': value['dataSources'],
        'sections': value['sections'],
        'filters': value['filters'],
    };
}

