/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ReportsScoutingPostRequest
 */
export interface ApiV1ReportsScoutingPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiV1ReportsScoutingPostRequest
     */
    playerId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ReportsScoutingPostRequest
     */
    prospectId?: number;
    /**
     * 
     * @type {Date}
     * @memberof ApiV1ReportsScoutingPostRequest
     */
    reportDate?: Date;
    /**
     * 
     * @type {ApiV1ReportsScoutingPostRequestEventTypeEnum}
     * @memberof ApiV1ReportsScoutingPostRequest
     */
    eventType?: ApiV1ReportsScoutingPostRequestEventTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ReportsScoutingPostRequest
     */
    overallPresent?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ReportsScoutingPostRequest
     */
    overallFuture?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ReportsScoutingPostRequest
     */
    hittingPresent?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ReportsScoutingPostRequest
     */
    hittingFuture?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ReportsScoutingPostRequest
     */
    notes?: string;
}


/**
 * @export
 */
export const ApiV1ReportsScoutingPostRequestEventTypeEnum = {
    Game: 'game',
    Showcase: 'showcase',
    Practice: 'practice',
    Workout: 'workout',
    Video: 'video'
} as const;
export type ApiV1ReportsScoutingPostRequestEventTypeEnum = typeof ApiV1ReportsScoutingPostRequestEventTypeEnum[keyof typeof ApiV1ReportsScoutingPostRequestEventTypeEnum];


/**
 * Check if a given object implements the ApiV1ReportsScoutingPostRequest interface.
 */
export function instanceOfApiV1ReportsScoutingPostRequest(value: object): value is ApiV1ReportsScoutingPostRequest {
    return true;
}

export function ApiV1ReportsScoutingPostRequestFromJSON(json: any): ApiV1ReportsScoutingPostRequest {
    return ApiV1ReportsScoutingPostRequestFromJSONTyped(json, false);
}

export function ApiV1ReportsScoutingPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ReportsScoutingPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'playerId': json['player_id'] == null ? undefined : json['player_id'],
        'prospectId': json['prospect_id'] == null ? undefined : json['prospect_id'],
        'reportDate': json['report_date'] == null ? undefined : (new Date(json['report_date'])),
        'eventType': json['event_type'] == null ? undefined : json['event_type'],
        'overallPresent': json['overall_present'] == null ? undefined : json['overall_present'],
        'overallFuture': json['overall_future'] == null ? undefined : json['overall_future'],
        'hittingPresent': json['hitting_present'] == null ? undefined : json['hitting_present'],
        'hittingFuture': json['hitting_future'] == null ? undefined : json['hitting_future'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function ApiV1ReportsScoutingPostRequestToJSON(json: any): ApiV1ReportsScoutingPostRequest {
    return ApiV1ReportsScoutingPostRequestToJSONTyped(json, false);
}

export function ApiV1ReportsScoutingPostRequestToJSONTyped(value?: ApiV1ReportsScoutingPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'player_id': value['playerId'],
        'prospect_id': value['prospectId'],
        'report_date': value['reportDate'] == null ? value['reportDate'] : value['reportDate'].toISOString().substring(0,10),
        'event_type': value['eventType'],
        'overall_present': value['overallPresent'],
        'overall_future': value['overallFuture'],
        'hitting_present': value['hittingPresent'],
        'hitting_future': value['hittingFuture'],
        'notes': value['notes'],
    };
}

