/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1SchedulesSectionsSectionIdActivitiesPostRequest
 */
export interface ApiV1SchedulesSectionsSectionIdActivitiesPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1SchedulesSectionsSectionIdActivitiesPostRequest
     */
    time: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1SchedulesSectionsSectionIdActivitiesPostRequest
     */
    activity: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1SchedulesSectionsSectionIdActivitiesPostRequest
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1SchedulesSectionsSectionIdActivitiesPostRequest
     */
    notes?: string;
}

/**
 * Check if a given object implements the ApiV1SchedulesSectionsSectionIdActivitiesPostRequest interface.
 */
export function instanceOfApiV1SchedulesSectionsSectionIdActivitiesPostRequest(value: object): value is ApiV1SchedulesSectionsSectionIdActivitiesPostRequest {
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('activity' in value) || value['activity'] === undefined) return false;
    return true;
}

export function ApiV1SchedulesSectionsSectionIdActivitiesPostRequestFromJSON(json: any): ApiV1SchedulesSectionsSectionIdActivitiesPostRequest {
    return ApiV1SchedulesSectionsSectionIdActivitiesPostRequestFromJSONTyped(json, false);
}

export function ApiV1SchedulesSectionsSectionIdActivitiesPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SchedulesSectionsSectionIdActivitiesPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'],
        'activity': json['activity'],
        'location': json['location'] == null ? undefined : json['location'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function ApiV1SchedulesSectionsSectionIdActivitiesPostRequestToJSON(json: any): ApiV1SchedulesSectionsSectionIdActivitiesPostRequest {
    return ApiV1SchedulesSectionsSectionIdActivitiesPostRequestToJSONTyped(json, false);
}

export function ApiV1SchedulesSectionsSectionIdActivitiesPostRequestToJSONTyped(value?: ApiV1SchedulesSectionsSectionIdActivitiesPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'],
        'activity': value['activity'],
        'location': value['location'],
        'notes': value['notes'],
    };
}

