/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ReportsGeneratePdfPostRequest
 */
export interface ApiV1ReportsGeneratePdfPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ReportsGeneratePdfPostRequest
     */
    reportId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ReportsGeneratePdfPostRequest
     */
    reportType?: string;
}

/**
 * Check if a given object implements the ApiV1ReportsGeneratePdfPostRequest interface.
 */
export function instanceOfApiV1ReportsGeneratePdfPostRequest(value: object): value is ApiV1ReportsGeneratePdfPostRequest {
    return true;
}

export function ApiV1ReportsGeneratePdfPostRequestFromJSON(json: any): ApiV1ReportsGeneratePdfPostRequest {
    return ApiV1ReportsGeneratePdfPostRequestFromJSONTyped(json, false);
}

export function ApiV1ReportsGeneratePdfPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ReportsGeneratePdfPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reportId': json['report_id'] == null ? undefined : json['report_id'],
        'reportType': json['report_type'] == null ? undefined : json['report_type'],
    };
}

export function ApiV1ReportsGeneratePdfPostRequestToJSON(json: any): ApiV1ReportsGeneratePdfPostRequest {
    return ApiV1ReportsGeneratePdfPostRequestToJSONTyped(json, false);
}

export function ApiV1ReportsGeneratePdfPostRequestToJSONTyped(value?: ApiV1ReportsGeneratePdfPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'report_id': value['reportId'],
        'report_type': value['reportType'],
    };
}

