/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1TeamsPermissionsPostRequest
 */
export interface ApiV1TeamsPermissionsPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiV1TeamsPermissionsPostRequest
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsPermissionsPostRequest
     */
    permissionType: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1TeamsPermissionsPostRequest
     */
    isGranted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ApiV1TeamsPermissionsPostRequest
     */
    expiresAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsPermissionsPostRequest
     */
    notes?: string;
}

/**
 * Check if a given object implements the ApiV1TeamsPermissionsPostRequest interface.
 */
export function instanceOfApiV1TeamsPermissionsPostRequest(value: object): value is ApiV1TeamsPermissionsPostRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('permissionType' in value) || value['permissionType'] === undefined) return false;
    return true;
}

export function ApiV1TeamsPermissionsPostRequestFromJSON(json: any): ApiV1TeamsPermissionsPostRequest {
    return ApiV1TeamsPermissionsPostRequestFromJSONTyped(json, false);
}

export function ApiV1TeamsPermissionsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1TeamsPermissionsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'permissionType': json['permission_type'],
        'isGranted': json['is_granted'] == null ? undefined : json['is_granted'],
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function ApiV1TeamsPermissionsPostRequestToJSON(json: any): ApiV1TeamsPermissionsPostRequest {
    return ApiV1TeamsPermissionsPostRequestToJSONTyped(json, false);
}

export function ApiV1TeamsPermissionsPostRequestToJSONTyped(value?: ApiV1TeamsPermissionsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'permission_type': value['permissionType'],
        'is_granted': value['isGranted'],
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'notes': value['notes'],
    };
}

