/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1AuthAdminUsersUserIdResetPasswordPutRequest
 */
export interface ApiV1AuthAdminUsersUserIdResetPasswordPutRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthAdminUsersUserIdResetPasswordPutRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the ApiV1AuthAdminUsersUserIdResetPasswordPutRequest interface.
 */
export function instanceOfApiV1AuthAdminUsersUserIdResetPasswordPutRequest(value: object): value is ApiV1AuthAdminUsersUserIdResetPasswordPutRequest {
    return true;
}

export function ApiV1AuthAdminUsersUserIdResetPasswordPutRequestFromJSON(json: any): ApiV1AuthAdminUsersUserIdResetPasswordPutRequest {
    return ApiV1AuthAdminUsersUserIdResetPasswordPutRequestFromJSONTyped(json, false);
}

export function ApiV1AuthAdminUsersUserIdResetPasswordPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AuthAdminUsersUserIdResetPasswordPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function ApiV1AuthAdminUsersUserIdResetPasswordPutRequestToJSON(json: any): ApiV1AuthAdminUsersUserIdResetPasswordPutRequest {
    return ApiV1AuthAdminUsersUserIdResetPasswordPutRequestToJSONTyped(json, false);
}

export function ApiV1AuthAdminUsersUserIdResetPasswordPutRequestToJSONTyped(value?: ApiV1AuthAdminUsersUserIdResetPasswordPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
    };
}

