/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1TeamsBrandingPutRequest
 */
export interface ApiV1TeamsBrandingPutRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsBrandingPutRequest
     */
    primaryColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsBrandingPutRequest
     */
    secondaryColor?: string;
}

/**
 * Check if a given object implements the ApiV1TeamsBrandingPutRequest interface.
 */
export function instanceOfApiV1TeamsBrandingPutRequest(value: object): value is ApiV1TeamsBrandingPutRequest {
    return true;
}

export function ApiV1TeamsBrandingPutRequestFromJSON(json: any): ApiV1TeamsBrandingPutRequest {
    return ApiV1TeamsBrandingPutRequestFromJSONTyped(json, false);
}

export function ApiV1TeamsBrandingPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1TeamsBrandingPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'primaryColor': json['primary_color'] == null ? undefined : json['primary_color'],
        'secondaryColor': json['secondary_color'] == null ? undefined : json['secondary_color'],
    };
}

export function ApiV1TeamsBrandingPutRequestToJSON(json: any): ApiV1TeamsBrandingPutRequest {
    return ApiV1TeamsBrandingPutRequestToJSONTyped(json, false);
}

export function ApiV1TeamsBrandingPutRequestToJSONTyped(value?: ApiV1TeamsBrandingPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'primary_color': value['primaryColor'],
        'secondary_color': value['secondaryColor'],
    };
}

