/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1LocationsPostRequest
 */
export interface ApiV1LocationsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1LocationsPostRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1LocationsPostRequest
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1LocationsPostRequest
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1LocationsPostRequest
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1LocationsPostRequest
     */
    zipCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1LocationsPostRequest
     */
    locationType?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1LocationsPostRequest
     */
    capacity?: number;
}

/**
 * Check if a given object implements the ApiV1LocationsPostRequest interface.
 */
export function instanceOfApiV1LocationsPostRequest(value: object): value is ApiV1LocationsPostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ApiV1LocationsPostRequestFromJSON(json: any): ApiV1LocationsPostRequest {
    return ApiV1LocationsPostRequestFromJSONTyped(json, false);
}

export function ApiV1LocationsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1LocationsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'zipCode': json['zip_code'] == null ? undefined : json['zip_code'],
        'locationType': json['location_type'] == null ? undefined : json['location_type'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
    };
}

export function ApiV1LocationsPostRequestToJSON(json: any): ApiV1LocationsPostRequest {
    return ApiV1LocationsPostRequestToJSONTyped(json, false);
}

export function ApiV1LocationsPostRequestToJSONTyped(value?: ApiV1LocationsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'address': value['address'],
        'city': value['city'],
        'state': value['state'],
        'zip_code': value['zipCode'],
        'location_type': value['locationType'],
        'capacity': value['capacity'],
    };
}

