/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1AuthChangePasswordPutRequest
 */
export interface ApiV1AuthChangePasswordPutRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthChangePasswordPutRequest
     */
    currentPassword: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthChangePasswordPutRequest
     */
    newPassword: string;
}

/**
 * Check if a given object implements the ApiV1AuthChangePasswordPutRequest interface.
 */
export function instanceOfApiV1AuthChangePasswordPutRequest(value: object): value is ApiV1AuthChangePasswordPutRequest {
    if (!('currentPassword' in value) || value['currentPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function ApiV1AuthChangePasswordPutRequestFromJSON(json: any): ApiV1AuthChangePasswordPutRequest {
    return ApiV1AuthChangePasswordPutRequestFromJSONTyped(json, false);
}

export function ApiV1AuthChangePasswordPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AuthChangePasswordPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['current_password'],
        'newPassword': json['new_password'],
    };
}

export function ApiV1AuthChangePasswordPutRequestToJSON(json: any): ApiV1AuthChangePasswordPutRequest {
    return ApiV1AuthChangePasswordPutRequestToJSONTyped(json, false);
}

export function ApiV1AuthChangePasswordPutRequestToJSONTyped(value?: ApiV1AuthChangePasswordPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_password': value['currentPassword'],
        'new_password': value['newPassword'],
    };
}

