/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1DepthChartsPositionsPositionIdPlayersPostRequest
 */
export interface ApiV1DepthChartsPositionsPositionIdPlayersPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiV1DepthChartsPositionsPositionIdPlayersPostRequest
     */
    playerId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1DepthChartsPositionsPositionIdPlayersPostRequest
     */
    rank?: number;
}

/**
 * Check if a given object implements the ApiV1DepthChartsPositionsPositionIdPlayersPostRequest interface.
 */
export function instanceOfApiV1DepthChartsPositionsPositionIdPlayersPostRequest(value: object): value is ApiV1DepthChartsPositionsPositionIdPlayersPostRequest {
    return true;
}

export function ApiV1DepthChartsPositionsPositionIdPlayersPostRequestFromJSON(json: any): ApiV1DepthChartsPositionsPositionIdPlayersPostRequest {
    return ApiV1DepthChartsPositionsPositionIdPlayersPostRequestFromJSONTyped(json, false);
}

export function ApiV1DepthChartsPositionsPositionIdPlayersPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1DepthChartsPositionsPositionIdPlayersPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'playerId': json['player_id'] == null ? undefined : json['player_id'],
        'rank': json['rank'] == null ? undefined : json['rank'],
    };
}

export function ApiV1DepthChartsPositionsPositionIdPlayersPostRequestToJSON(json: any): ApiV1DepthChartsPositionsPositionIdPlayersPostRequest {
    return ApiV1DepthChartsPositionsPositionIdPlayersPostRequestToJSONTyped(json, false);
}

export function ApiV1DepthChartsPositionsPositionIdPlayersPostRequestToJSONTyped(value?: ApiV1DepthChartsPositionsPositionIdPlayersPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'player_id': value['playerId'],
        'rank': value['rank'],
    };
}

