/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1CoachesPostRequest
 */
export interface ApiV1CoachesPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1CoachesPostRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1CoachesPostRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1CoachesPostRequest
     */
    schoolName: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1CoachesPostRequest
     */
    position?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1CoachesPostRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1CoachesPostRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1CoachesPostRequest
     */
    notes?: string;
}

/**
 * Check if a given object implements the ApiV1CoachesPostRequest interface.
 */
export function instanceOfApiV1CoachesPostRequest(value: object): value is ApiV1CoachesPostRequest {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('schoolName' in value) || value['schoolName'] === undefined) return false;
    return true;
}

export function ApiV1CoachesPostRequestFromJSON(json: any): ApiV1CoachesPostRequest {
    return ApiV1CoachesPostRequestFromJSONTyped(json, false);
}

export function ApiV1CoachesPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1CoachesPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'schoolName': json['school_name'],
        'position': json['position'] == null ? undefined : json['position'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function ApiV1CoachesPostRequestToJSON(json: any): ApiV1CoachesPostRequest {
    return ApiV1CoachesPostRequestToJSONTyped(json, false);
}

export function ApiV1CoachesPostRequestToJSONTyped(value?: ApiV1CoachesPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'school_name': value['schoolName'],
        'position': value['position'],
        'email': value['email'],
        'phone': value['phone'],
        'notes': value['notes'],
    };
}

