/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1AuthLoginPostRequest
 */
export interface ApiV1AuthLoginPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthLoginPostRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthLoginPostRequest
     */
    password: string;
}

/**
 * Check if a given object implements the ApiV1AuthLoginPostRequest interface.
 */
export function instanceOfApiV1AuthLoginPostRequest(value: object): value is ApiV1AuthLoginPostRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function ApiV1AuthLoginPostRequestFromJSON(json: any): ApiV1AuthLoginPostRequest {
    return ApiV1AuthLoginPostRequestFromJSONTyped(json, false);
}

export function ApiV1AuthLoginPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AuthLoginPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function ApiV1AuthLoginPostRequestToJSON(json: any): ApiV1AuthLoginPostRequest {
    return ApiV1AuthLoginPostRequestToJSONTyped(json, false);
}

export function ApiV1AuthLoginPostRequestToJSONTyped(value?: ApiV1AuthLoginPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

