/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ScheduleTemplatesPostRequest
 */
export interface ApiV1ScheduleTemplatesPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ScheduleTemplatesPostRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ScheduleTemplatesPostRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the ApiV1ScheduleTemplatesPostRequest interface.
 */
export function instanceOfApiV1ScheduleTemplatesPostRequest(value: object): value is ApiV1ScheduleTemplatesPostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ApiV1ScheduleTemplatesPostRequestFromJSON(json: any): ApiV1ScheduleTemplatesPostRequest {
    return ApiV1ScheduleTemplatesPostRequestFromJSONTyped(json, false);
}

export function ApiV1ScheduleTemplatesPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ScheduleTemplatesPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ApiV1ScheduleTemplatesPostRequestToJSON(json: any): ApiV1ScheduleTemplatesPostRequest {
    return ApiV1ScheduleTemplatesPostRequestToJSONTyped(json, false);
}

export function ApiV1ScheduleTemplatesPostRequestToJSONTyped(value?: ApiV1ScheduleTemplatesPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

