/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ScheduleEventsPostRequest
 */
export interface ApiV1ScheduleEventsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ScheduleEventsPostRequest
     */
    title?: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiV1ScheduleEventsPostRequest
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiV1ScheduleEventsPostRequest
     */
    endDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ScheduleEventsPostRequest
     */
    locationId?: number;
}

/**
 * Check if a given object implements the ApiV1ScheduleEventsPostRequest interface.
 */
export function instanceOfApiV1ScheduleEventsPostRequest(value: object): value is ApiV1ScheduleEventsPostRequest {
    return true;
}

export function ApiV1ScheduleEventsPostRequestFromJSON(json: any): ApiV1ScheduleEventsPostRequest {
    return ApiV1ScheduleEventsPostRequestFromJSONTyped(json, false);
}

export function ApiV1ScheduleEventsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ScheduleEventsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'locationId': json['location_id'] == null ? undefined : json['location_id'],
    };
}

export function ApiV1ScheduleEventsPostRequestToJSON(json: any): ApiV1ScheduleEventsPostRequest {
    return ApiV1ScheduleEventsPostRequestToJSONTyped(json, false);
}

export function ApiV1ScheduleEventsPostRequestToJSONTyped(value?: ApiV1ScheduleEventsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'start_date': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString().substring(0,10),
        'end_date': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'location_id': value['locationId'],
    };
}

