/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1TeamsPermissionsIdPutRequest
 */
export interface ApiV1TeamsPermissionsIdPutRequest {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1TeamsPermissionsIdPutRequest
     */
    isGranted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsPermissionsIdPutRequest
     */
    expiresAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsPermissionsIdPutRequest
     */
    notes?: string;
}

/**
 * Check if a given object implements the ApiV1TeamsPermissionsIdPutRequest interface.
 */
export function instanceOfApiV1TeamsPermissionsIdPutRequest(value: object): value is ApiV1TeamsPermissionsIdPutRequest {
    return true;
}

export function ApiV1TeamsPermissionsIdPutRequestFromJSON(json: any): ApiV1TeamsPermissionsIdPutRequest {
    return ApiV1TeamsPermissionsIdPutRequestFromJSONTyped(json, false);
}

export function ApiV1TeamsPermissionsIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1TeamsPermissionsIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isGranted': json['is_granted'] == null ? undefined : json['is_granted'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function ApiV1TeamsPermissionsIdPutRequestToJSON(json: any): ApiV1TeamsPermissionsIdPutRequest {
    return ApiV1TeamsPermissionsIdPutRequestToJSONTyped(json, false);
}

export function ApiV1TeamsPermissionsIdPutRequestToJSONTyped(value?: ApiV1TeamsPermissionsIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_granted': value['isGranted'],
        'expires_at': value['expiresAt'],
        'notes': value['notes'],
    };
}

