/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ScheduleTemplatesIdPutRequest
 */
export interface ApiV1ScheduleTemplatesIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ScheduleTemplatesIdPutRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ScheduleTemplatesIdPutRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the ApiV1ScheduleTemplatesIdPutRequest interface.
 */
export function instanceOfApiV1ScheduleTemplatesIdPutRequest(value: object): value is ApiV1ScheduleTemplatesIdPutRequest {
    return true;
}

export function ApiV1ScheduleTemplatesIdPutRequestFromJSON(json: any): ApiV1ScheduleTemplatesIdPutRequest {
    return ApiV1ScheduleTemplatesIdPutRequestFromJSONTyped(json, false);
}

export function ApiV1ScheduleTemplatesIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ScheduleTemplatesIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ApiV1ScheduleTemplatesIdPutRequestToJSON(json: any): ApiV1ScheduleTemplatesIdPutRequest {
    return ApiV1ScheduleTemplatesIdPutRequestToJSONTyped(json, false);
}

export function ApiV1ScheduleTemplatesIdPutRequestToJSONTyped(value?: ApiV1ScheduleTemplatesIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

