/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1AuthRegisterPostRequest
 */
export interface ApiV1AuthRegisterPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthRegisterPostRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthRegisterPostRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthRegisterPostRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthRegisterPostRequest
     */
    lastName: string;
    /**
     * 
     * @type {ApiV1AuthRegisterPostRequestRoleEnum}
     * @memberof ApiV1AuthRegisterPostRequest
     */
    role: ApiV1AuthRegisterPostRequestRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthRegisterPostRequest
     */
    phone?: string;
}


/**
 * @export
 */
export const ApiV1AuthRegisterPostRequestRoleEnum = {
    HeadCoach: 'head_coach',
    AssistantCoach: 'assistant_coach'
} as const;
export type ApiV1AuthRegisterPostRequestRoleEnum = typeof ApiV1AuthRegisterPostRequestRoleEnum[keyof typeof ApiV1AuthRegisterPostRequestRoleEnum];


/**
 * Check if a given object implements the ApiV1AuthRegisterPostRequest interface.
 */
export function instanceOfApiV1AuthRegisterPostRequest(value: object): value is ApiV1AuthRegisterPostRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function ApiV1AuthRegisterPostRequestFromJSON(json: any): ApiV1AuthRegisterPostRequest {
    return ApiV1AuthRegisterPostRequestFromJSONTyped(json, false);
}

export function ApiV1AuthRegisterPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AuthRegisterPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'role': json['role'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function ApiV1AuthRegisterPostRequestToJSON(json: any): ApiV1AuthRegisterPostRequest {
    return ApiV1AuthRegisterPostRequestToJSONTyped(json, false);
}

export function ApiV1AuthRegisterPostRequestToJSONTyped(value?: ApiV1AuthRegisterPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'role': value['role'],
        'phone': value['phone'],
    };
}

