/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1DepthChartsPostRequest
 */
export interface ApiV1DepthChartsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1DepthChartsPostRequest
     */
    name: string;
}

/**
 * Check if a given object implements the ApiV1DepthChartsPostRequest interface.
 */
export function instanceOfApiV1DepthChartsPostRequest(value: object): value is ApiV1DepthChartsPostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ApiV1DepthChartsPostRequestFromJSON(json: any): ApiV1DepthChartsPostRequest {
    return ApiV1DepthChartsPostRequestFromJSONTyped(json, false);
}

export function ApiV1DepthChartsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1DepthChartsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function ApiV1DepthChartsPostRequestToJSON(json: any): ApiV1DepthChartsPostRequest {
    return ApiV1DepthChartsPostRequestToJSONTyped(json, false);
}

export function ApiV1DepthChartsPostRequestToJSONTyped(value?: ApiV1DepthChartsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

