/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1AuthCsrfTokenGet200Response
 */
export interface ApiV1AuthCsrfTokenGet200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthCsrfTokenGet200Response
     */
    token?: string;
}

/**
 * Check if a given object implements the ApiV1AuthCsrfTokenGet200Response interface.
 */
export function instanceOfApiV1AuthCsrfTokenGet200Response(value: object): value is ApiV1AuthCsrfTokenGet200Response {
    return true;
}

export function ApiV1AuthCsrfTokenGet200ResponseFromJSON(json: any): ApiV1AuthCsrfTokenGet200Response {
    return ApiV1AuthCsrfTokenGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1AuthCsrfTokenGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AuthCsrfTokenGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function ApiV1AuthCsrfTokenGet200ResponseToJSON(json: any): ApiV1AuthCsrfTokenGet200Response {
    return ApiV1AuthCsrfTokenGet200ResponseToJSONTyped(json, false);
}

export function ApiV1AuthCsrfTokenGet200ResponseToJSONTyped(value?: ApiV1AuthCsrfTokenGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

