/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { Player } from './Player';
import {
    PlayerFromJSON,
    PlayerFromJSONTyped,
    PlayerToJSON,
    PlayerToJSONTyped,
} from './Player';

/**
 * 
 * @export
 * @interface ApiV1PlayersGet200Response
 */
export interface ApiV1PlayersGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1PlayersGet200Response
     */
    success?: boolean;
    /**
     * 
     * @type {Array<Player>}
     * @memberof ApiV1PlayersGet200Response
     */
    data?: Array<Player>;
    /**
     * 
     * @type {Pagination}
     * @memberof ApiV1PlayersGet200Response
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the ApiV1PlayersGet200Response interface.
 */
export function instanceOfApiV1PlayersGet200Response(value: object): value is ApiV1PlayersGet200Response {
    return true;
}

export function ApiV1PlayersGet200ResponseFromJSON(json: any): ApiV1PlayersGet200Response {
    return ApiV1PlayersGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1PlayersGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1PlayersGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PlayerFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function ApiV1PlayersGet200ResponseToJSON(json: any): ApiV1PlayersGet200Response {
    return ApiV1PlayersGet200ResponseToJSONTyped(json, false);
}

export function ApiV1PlayersGet200ResponseToJSONTyped(value?: ApiV1PlayersGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PlayerToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

