/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ProspectsIdMediaPostRequest1
 */
export interface ApiV1ProspectsIdMediaPostRequest1 {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ProspectsIdMediaPostRequest1
     */
    url: string;
    /**
     * 
     * @type {ApiV1ProspectsIdMediaPostRequest1MediaTypeEnum}
     * @memberof ApiV1ProspectsIdMediaPostRequest1
     */
    mediaType: ApiV1ProspectsIdMediaPostRequest1MediaTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ProspectsIdMediaPostRequest1
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ProspectsIdMediaPostRequest1
     */
    description?: string;
}


/**
 * @export
 */
export const ApiV1ProspectsIdMediaPostRequest1MediaTypeEnum = {
    Video: 'video',
    Photo: 'photo',
    Document: 'document'
} as const;
export type ApiV1ProspectsIdMediaPostRequest1MediaTypeEnum = typeof ApiV1ProspectsIdMediaPostRequest1MediaTypeEnum[keyof typeof ApiV1ProspectsIdMediaPostRequest1MediaTypeEnum];


/**
 * Check if a given object implements the ApiV1ProspectsIdMediaPostRequest1 interface.
 */
export function instanceOfApiV1ProspectsIdMediaPostRequest1(value: object): value is ApiV1ProspectsIdMediaPostRequest1 {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('mediaType' in value) || value['mediaType'] === undefined) return false;
    return true;
}

export function ApiV1ProspectsIdMediaPostRequest1FromJSON(json: any): ApiV1ProspectsIdMediaPostRequest1 {
    return ApiV1ProspectsIdMediaPostRequest1FromJSONTyped(json, false);
}

export function ApiV1ProspectsIdMediaPostRequest1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ProspectsIdMediaPostRequest1 {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'mediaType': json['media_type'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ApiV1ProspectsIdMediaPostRequest1ToJSON(json: any): ApiV1ProspectsIdMediaPostRequest1 {
    return ApiV1ProspectsIdMediaPostRequest1ToJSONTyped(json, false);
}

export function ApiV1ProspectsIdMediaPostRequest1ToJSONTyped(value?: ApiV1ProspectsIdMediaPostRequest1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'media_type': value['mediaType'],
        'title': value['title'],
        'description': value['description'],
    };
}

