/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1AuthMePutRequest
 */
export interface ApiV1AuthMePutRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthMePutRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthMePutRequest
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AuthMePutRequest
     */
    phone?: string;
}

/**
 * Check if a given object implements the ApiV1AuthMePutRequest interface.
 */
export function instanceOfApiV1AuthMePutRequest(value: object): value is ApiV1AuthMePutRequest {
    return true;
}

export function ApiV1AuthMePutRequestFromJSON(json: any): ApiV1AuthMePutRequest {
    return ApiV1AuthMePutRequestFromJSONTyped(json, false);
}

export function ApiV1AuthMePutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AuthMePutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function ApiV1AuthMePutRequestToJSON(json: any): ApiV1AuthMePutRequest {
    return ApiV1AuthMePutRequestToJSONTyped(json, false);
}

export function ApiV1AuthMePutRequestToJSONTyped(value?: ApiV1AuthMePutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'phone': value['phone'],
    };
}

