/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1SettingsTwoFactorVerifyPostRequest
 */
export interface ApiV1SettingsTwoFactorVerifyPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1SettingsTwoFactorVerifyPostRequest
     */
    code: string;
}

/**
 * Check if a given object implements the ApiV1SettingsTwoFactorVerifyPostRequest interface.
 */
export function instanceOfApiV1SettingsTwoFactorVerifyPostRequest(value: object): value is ApiV1SettingsTwoFactorVerifyPostRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ApiV1SettingsTwoFactorVerifyPostRequestFromJSON(json: any): ApiV1SettingsTwoFactorVerifyPostRequest {
    return ApiV1SettingsTwoFactorVerifyPostRequestFromJSONTyped(json, false);
}

export function ApiV1SettingsTwoFactorVerifyPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SettingsTwoFactorVerifyPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function ApiV1SettingsTwoFactorVerifyPostRequestToJSON(json: any): ApiV1SettingsTwoFactorVerifyPostRequest {
    return ApiV1SettingsTwoFactorVerifyPostRequestToJSONTyped(json, false);
}

export function ApiV1SettingsTwoFactorVerifyPostRequestToJSONTyped(value?: ApiV1SettingsTwoFactorVerifyPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

