/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1TeamsMePutRequest
 */
export interface ApiV1TeamsMePutRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsMePutRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsMePutRequest
     */
    programName?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsMePutRequest
     */
    conference?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsMePutRequest
     */
    division?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsMePutRequest
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsMePutRequest
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsMePutRequest
     */
    primaryColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsMePutRequest
     */
    secondaryColor?: string;
}

/**
 * Check if a given object implements the ApiV1TeamsMePutRequest interface.
 */
export function instanceOfApiV1TeamsMePutRequest(value: object): value is ApiV1TeamsMePutRequest {
    return true;
}

export function ApiV1TeamsMePutRequestFromJSON(json: any): ApiV1TeamsMePutRequest {
    return ApiV1TeamsMePutRequestFromJSONTyped(json, false);
}

export function ApiV1TeamsMePutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1TeamsMePutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'programName': json['program_name'] == null ? undefined : json['program_name'],
        'conference': json['conference'] == null ? undefined : json['conference'],
        'division': json['division'] == null ? undefined : json['division'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'primaryColor': json['primary_color'] == null ? undefined : json['primary_color'],
        'secondaryColor': json['secondary_color'] == null ? undefined : json['secondary_color'],
    };
}

export function ApiV1TeamsMePutRequestToJSON(json: any): ApiV1TeamsMePutRequest {
    return ApiV1TeamsMePutRequestToJSONTyped(json, false);
}

export function ApiV1TeamsMePutRequestToJSONTyped(value?: ApiV1TeamsMePutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'program_name': value['programName'],
        'conference': value['conference'],
        'division': value['division'],
        'city': value['city'],
        'state': value['state'],
        'primary_color': value['primaryColor'],
        'secondary_color': value['secondaryColor'],
    };
}

