/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1SchedulesByIdIdPutRequest
 */
export interface ApiV1SchedulesByIdIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1SchedulesByIdIdPutRequest
     */
    teamName?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1SchedulesByIdIdPutRequest
     */
    programName?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1SchedulesByIdIdPutRequest
     */
    date?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1SchedulesByIdIdPutRequest
     */
    sections?: Array<string>;
}

/**
 * Check if a given object implements the ApiV1SchedulesByIdIdPutRequest interface.
 */
export function instanceOfApiV1SchedulesByIdIdPutRequest(value: object): value is ApiV1SchedulesByIdIdPutRequest {
    return true;
}

export function ApiV1SchedulesByIdIdPutRequestFromJSON(json: any): ApiV1SchedulesByIdIdPutRequest {
    return ApiV1SchedulesByIdIdPutRequestFromJSONTyped(json, false);
}

export function ApiV1SchedulesByIdIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SchedulesByIdIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'teamName': json['team_name'] == null ? undefined : json['team_name'],
        'programName': json['program_name'] == null ? undefined : json['program_name'],
        'date': json['date'] == null ? undefined : json['date'],
        'sections': json['sections'] == null ? undefined : json['sections'],
    };
}

export function ApiV1SchedulesByIdIdPutRequestToJSON(json: any): ApiV1SchedulesByIdIdPutRequest {
    return ApiV1SchedulesByIdIdPutRequestToJSONTyped(json, false);
}

export function ApiV1SchedulesByIdIdPutRequestToJSONTyped(value?: ApiV1SchedulesByIdIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'team_name': value['teamName'],
        'program_name': value['programName'],
        'date': value['date'],
        'sections': value['sections'],
    };
}

