/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1SchedulesPostRequest
 */
export interface ApiV1SchedulesPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1SchedulesPostRequest
     */
    teamName: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1SchedulesPostRequest
     */
    programName: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiV1SchedulesPostRequest
     */
    date: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1SchedulesPostRequest
     */
    sections: Array<string>;
}

/**
 * Check if a given object implements the ApiV1SchedulesPostRequest interface.
 */
export function instanceOfApiV1SchedulesPostRequest(value: object): value is ApiV1SchedulesPostRequest {
    if (!('teamName' in value) || value['teamName'] === undefined) return false;
    if (!('programName' in value) || value['programName'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('sections' in value) || value['sections'] === undefined) return false;
    return true;
}

export function ApiV1SchedulesPostRequestFromJSON(json: any): ApiV1SchedulesPostRequest {
    return ApiV1SchedulesPostRequestFromJSONTyped(json, false);
}

export function ApiV1SchedulesPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SchedulesPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'teamName': json['team_name'],
        'programName': json['program_name'],
        'date': (new Date(json['date'])),
        'sections': json['sections'],
    };
}

export function ApiV1SchedulesPostRequestToJSON(json: any): ApiV1SchedulesPostRequest {
    return ApiV1SchedulesPostRequestToJSONTyped(json, false);
}

export function ApiV1SchedulesPostRequestToJSONTyped(value?: ApiV1SchedulesPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'team_name': value['teamName'],
        'program_name': value['programName'],
        'date': value['date'].toISOString().substring(0,10),
        'sections': value['sections'],
    };
}

