/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { Prospect } from './Prospect';
import {
    ProspectFromJSON,
    ProspectFromJSONTyped,
    ProspectToJSON,
    ProspectToJSONTyped,
} from './Prospect';

/**
 * 
 * @export
 * @interface ApiV1ProspectsGet200Response
 */
export interface ApiV1ProspectsGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ProspectsGet200Response
     */
    success?: boolean;
    /**
     * 
     * @type {Array<Prospect>}
     * @memberof ApiV1ProspectsGet200Response
     */
    data?: Array<Prospect>;
    /**
     * 
     * @type {Pagination}
     * @memberof ApiV1ProspectsGet200Response
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the ApiV1ProspectsGet200Response interface.
 */
export function instanceOfApiV1ProspectsGet200Response(value: object): value is ApiV1ProspectsGet200Response {
    return true;
}

export function ApiV1ProspectsGet200ResponseFromJSON(json: any): ApiV1ProspectsGet200Response {
    return ApiV1ProspectsGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1ProspectsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ProspectsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ProspectFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function ApiV1ProspectsGet200ResponseToJSON(json: any): ApiV1ProspectsGet200Response {
    return ApiV1ProspectsGet200ResponseToJSONTyped(json, false);
}

export function ApiV1ProspectsGet200ResponseToJSONTyped(value?: ApiV1ProspectsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ProspectToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

