/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1GamesPostRequest
 */
export interface ApiV1GamesPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1GamesPostRequest
     */
    opponent?: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiV1GamesPostRequest
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof ApiV1GamesPostRequest
     */
    locationId?: number;
}

/**
 * Check if a given object implements the ApiV1GamesPostRequest interface.
 */
export function instanceOfApiV1GamesPostRequest(value: object): value is ApiV1GamesPostRequest {
    return true;
}

export function ApiV1GamesPostRequestFromJSON(json: any): ApiV1GamesPostRequest {
    return ApiV1GamesPostRequestFromJSONTyped(json, false);
}

export function ApiV1GamesPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1GamesPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'opponent': json['opponent'] == null ? undefined : json['opponent'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'locationId': json['location_id'] == null ? undefined : json['location_id'],
    };
}

export function ApiV1GamesPostRequestToJSON(json: any): ApiV1GamesPostRequest {
    return ApiV1GamesPostRequestToJSONTyped(json, false);
}

export function ApiV1GamesPostRequestToJSONTyped(value?: ApiV1GamesPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'opponent': value['opponent'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString().substring(0,10),
        'location_id': value['locationId'],
    };
}

