/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1PlayersBulkDeletePostRequest
 */
export interface ApiV1PlayersBulkDeletePostRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof ApiV1PlayersBulkDeletePostRequest
     */
    playerIds: Array<number>;
}

/**
 * Check if a given object implements the ApiV1PlayersBulkDeletePostRequest interface.
 */
export function instanceOfApiV1PlayersBulkDeletePostRequest(value: object): value is ApiV1PlayersBulkDeletePostRequest {
    if (!('playerIds' in value) || value['playerIds'] === undefined) return false;
    return true;
}

export function ApiV1PlayersBulkDeletePostRequestFromJSON(json: any): ApiV1PlayersBulkDeletePostRequest {
    return ApiV1PlayersBulkDeletePostRequestFromJSONTyped(json, false);
}

export function ApiV1PlayersBulkDeletePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1PlayersBulkDeletePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'playerIds': json['player_ids'],
    };
}

export function ApiV1PlayersBulkDeletePostRequestToJSON(json: any): ApiV1PlayersBulkDeletePostRequest {
    return ApiV1PlayersBulkDeletePostRequestToJSONTyped(json, false);
}

export function ApiV1PlayersBulkDeletePostRequestToJSONTyped(value?: ApiV1PlayersBulkDeletePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'player_ids': value['playerIds'],
    };
}

