/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface ApiV1AuthMeGet200Response
 */
export interface ApiV1AuthMeGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1AuthMeGet200Response
     */
    success?: boolean;
    /**
     * 
     * @type {User}
     * @memberof ApiV1AuthMeGet200Response
     */
    data?: User;
}

/**
 * Check if a given object implements the ApiV1AuthMeGet200Response interface.
 */
export function instanceOfApiV1AuthMeGet200Response(value: object): value is ApiV1AuthMeGet200Response {
    return true;
}

export function ApiV1AuthMeGet200ResponseFromJSON(json: any): ApiV1AuthMeGet200Response {
    return ApiV1AuthMeGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1AuthMeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AuthMeGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : UserFromJSON(json['data']),
    };
}

export function ApiV1AuthMeGet200ResponseToJSON(json: any): ApiV1AuthMeGet200Response {
    return ApiV1AuthMeGet200ResponseToJSONTyped(json, false);
}

export function ApiV1AuthMeGet200ResponseToJSONTyped(value?: ApiV1AuthMeGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': UserToJSON(value['data']),
    };
}

