/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ApiV1RecruitsPreferenceListsPostRequestOneOf } from './ApiV1RecruitsPreferenceListsPostRequestOneOf';
import {
    instanceOfApiV1RecruitsPreferenceListsPostRequestOneOf,
    ApiV1RecruitsPreferenceListsPostRequestOneOfFromJSON,
    ApiV1RecruitsPreferenceListsPostRequestOneOfFromJSONTyped,
    ApiV1RecruitsPreferenceListsPostRequestOneOfToJSON,
} from './ApiV1RecruitsPreferenceListsPostRequestOneOf';
import type { ApiV1RecruitsPreferenceListsPostRequestOneOf1 } from './ApiV1RecruitsPreferenceListsPostRequestOneOf1';
import {
    instanceOfApiV1RecruitsPreferenceListsPostRequestOneOf1,
    ApiV1RecruitsPreferenceListsPostRequestOneOf1FromJSON,
    ApiV1RecruitsPreferenceListsPostRequestOneOf1FromJSONTyped,
    ApiV1RecruitsPreferenceListsPostRequestOneOf1ToJSON,
} from './ApiV1RecruitsPreferenceListsPostRequestOneOf1';

/**
 * @type ApiV1RecruitsPreferenceListsPostRequest
 * 
 * @export
 */
export type ApiV1RecruitsPreferenceListsPostRequest = ApiV1RecruitsPreferenceListsPostRequestOneOf | ApiV1RecruitsPreferenceListsPostRequestOneOf1;

export function ApiV1RecruitsPreferenceListsPostRequestFromJSON(json: any): ApiV1RecruitsPreferenceListsPostRequest {
    return ApiV1RecruitsPreferenceListsPostRequestFromJSONTyped(json, false);
}

export function ApiV1RecruitsPreferenceListsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RecruitsPreferenceListsPostRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfApiV1RecruitsPreferenceListsPostRequestOneOf(json)) {
        return ApiV1RecruitsPreferenceListsPostRequestOneOfFromJSONTyped(json, true);
    }
    if (instanceOfApiV1RecruitsPreferenceListsPostRequestOneOf1(json)) {
        return ApiV1RecruitsPreferenceListsPostRequestOneOf1FromJSONTyped(json, true);
    }
    return {} as any;
}

export function ApiV1RecruitsPreferenceListsPostRequestToJSON(json: any): any {
    return ApiV1RecruitsPreferenceListsPostRequestToJSONTyped(json, false);
}

export function ApiV1RecruitsPreferenceListsPostRequestToJSONTyped(value?: ApiV1RecruitsPreferenceListsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfApiV1RecruitsPreferenceListsPostRequestOneOf(value)) {
        return ApiV1RecruitsPreferenceListsPostRequestOneOfToJSON(value as ApiV1RecruitsPreferenceListsPostRequestOneOf);
    }
    if (instanceOfApiV1RecruitsPreferenceListsPostRequestOneOf1(value)) {
        return ApiV1RecruitsPreferenceListsPostRequestOneOf1ToJSON(value as ApiV1RecruitsPreferenceListsPostRequestOneOf1);
    }
    return {};
}

