/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1RecruitsPreferenceListsPostRequestOneOf
 */
export interface ApiV1RecruitsPreferenceListsPostRequestOneOf {
    /**
     * 
     * @type {number}
     * @memberof ApiV1RecruitsPreferenceListsPostRequestOneOf
     */
    prospectId: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1RecruitsPreferenceListsPostRequestOneOf
     */
    listType?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1RecruitsPreferenceListsPostRequestOneOf
     */
    priority?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1RecruitsPreferenceListsPostRequestOneOf
     */
    notes?: string;
}

/**
 * Check if a given object implements the ApiV1RecruitsPreferenceListsPostRequestOneOf interface.
 */
export function instanceOfApiV1RecruitsPreferenceListsPostRequestOneOf(value: object): value is ApiV1RecruitsPreferenceListsPostRequestOneOf {
    if (!('prospectId' in value) || value['prospectId'] === undefined) return false;
    return true;
}

export function ApiV1RecruitsPreferenceListsPostRequestOneOfFromJSON(json: any): ApiV1RecruitsPreferenceListsPostRequestOneOf {
    return ApiV1RecruitsPreferenceListsPostRequestOneOfFromJSONTyped(json, false);
}

export function ApiV1RecruitsPreferenceListsPostRequestOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RecruitsPreferenceListsPostRequestOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'prospectId': json['prospect_id'],
        'listType': json['list_type'] == null ? undefined : json['list_type'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function ApiV1RecruitsPreferenceListsPostRequestOneOfToJSON(json: any): ApiV1RecruitsPreferenceListsPostRequestOneOf {
    return ApiV1RecruitsPreferenceListsPostRequestOneOfToJSONTyped(json, false);
}

export function ApiV1RecruitsPreferenceListsPostRequestOneOfToJSONTyped(value?: ApiV1RecruitsPreferenceListsPostRequestOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prospect_id': value['prospectId'],
        'list_type': value['listType'],
        'priority': value['priority'],
        'notes': value['notes'],
    };
}

