/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1RecruitsPreferenceListsIdPutRequest
 */
export interface ApiV1RecruitsPreferenceListsIdPutRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiV1RecruitsPreferenceListsIdPutRequest
     */
    priority?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1RecruitsPreferenceListsIdPutRequest
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1RecruitsPreferenceListsIdPutRequest
     */
    notes?: string;
}

/**
 * Check if a given object implements the ApiV1RecruitsPreferenceListsIdPutRequest interface.
 */
export function instanceOfApiV1RecruitsPreferenceListsIdPutRequest(value: object): value is ApiV1RecruitsPreferenceListsIdPutRequest {
    return true;
}

export function ApiV1RecruitsPreferenceListsIdPutRequestFromJSON(json: any): ApiV1RecruitsPreferenceListsIdPutRequest {
    return ApiV1RecruitsPreferenceListsIdPutRequestFromJSONTyped(json, false);
}

export function ApiV1RecruitsPreferenceListsIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RecruitsPreferenceListsIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'priority': json['priority'] == null ? undefined : json['priority'],
        'status': json['status'] == null ? undefined : json['status'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function ApiV1RecruitsPreferenceListsIdPutRequestToJSON(json: any): ApiV1RecruitsPreferenceListsIdPutRequest {
    return ApiV1RecruitsPreferenceListsIdPutRequestToJSONTyped(json, false);
}

export function ApiV1RecruitsPreferenceListsIdPutRequestToJSONTyped(value?: ApiV1RecruitsPreferenceListsIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'priority': value['priority'],
        'status': value['status'],
        'notes': value['notes'],
    };
}

