/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayerCreateInput
 */
export interface PlayerCreateInput {
    /**
     * 
     * @type {string}
     * @memberof PlayerCreateInput
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerCreateInput
     */
    lastName: string;
    /**
     * 
     * @type {PlayerCreateInputPositionEnum}
     * @memberof PlayerCreateInput
     */
    position: PlayerCreateInputPositionEnum;
    /**
     * 
     * @type {PlayerCreateInputSchoolTypeEnum}
     * @memberof PlayerCreateInput
     */
    schoolType?: PlayerCreateInputSchoolTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PlayerCreateInput
     */
    school?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerCreateInput
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerCreateInput
     */
    state?: string;
    /**
     * 
     * @type {number}
     * @memberof PlayerCreateInput
     */
    graduationYear?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerCreateInput
     */
    weight?: number;
    /**
     * 
     * @type {string}
     * @memberof PlayerCreateInput
     */
    height?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerCreateInput
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerCreateInput
     */
    phone?: string;
}


/**
 * @export
 */
export const PlayerCreateInputPositionEnum = {
    P: 'P',
    C: 'C',
    _1B: '1B',
    _2B: '2B',
    _3B: '3B',
    Ss: 'SS',
    Lf: 'LF',
    Cf: 'CF',
    Rf: 'RF',
    Of: 'OF',
    Dh: 'DH'
} as const;
export type PlayerCreateInputPositionEnum = typeof PlayerCreateInputPositionEnum[keyof typeof PlayerCreateInputPositionEnum];

/**
 * @export
 */
export const PlayerCreateInputSchoolTypeEnum = {
    Hs: 'HS',
    Coll: 'COLL'
} as const;
export type PlayerCreateInputSchoolTypeEnum = typeof PlayerCreateInputSchoolTypeEnum[keyof typeof PlayerCreateInputSchoolTypeEnum];


/**
 * Check if a given object implements the PlayerCreateInput interface.
 */
export function instanceOfPlayerCreateInput(value: object): value is PlayerCreateInput {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    return true;
}

export function PlayerCreateInputFromJSON(json: any): PlayerCreateInput {
    return PlayerCreateInputFromJSONTyped(json, false);
}

export function PlayerCreateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerCreateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'position': json['position'],
        'schoolType': json['school_type'] == null ? undefined : json['school_type'],
        'school': json['school'] == null ? undefined : json['school'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'graduationYear': json['graduation_year'] == null ? undefined : json['graduation_year'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'height': json['height'] == null ? undefined : json['height'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function PlayerCreateInputToJSON(json: any): PlayerCreateInput {
    return PlayerCreateInputToJSONTyped(json, false);
}

export function PlayerCreateInputToJSONTyped(value?: PlayerCreateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'position': value['position'],
        'school_type': value['schoolType'],
        'school': value['school'],
        'city': value['city'],
        'state': value['state'],
        'graduation_year': value['graduationYear'],
        'weight': value['weight'],
        'height': value['height'],
        'email': value['email'],
        'phone': value['phone'],
    };
}

