/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayerUpdateInput
 */
export interface PlayerUpdateInput {
    /**
     * 
     * @type {string}
     * @memberof PlayerUpdateInput
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerUpdateInput
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerUpdateInput
     */
    position?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerUpdateInput
     */
    schoolType?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerUpdateInput
     */
    school?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerUpdateInput
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerUpdateInput
     */
    state?: string;
    /**
     * 
     * @type {number}
     * @memberof PlayerUpdateInput
     */
    graduationYear?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerUpdateInput
     */
    weight?: number;
    /**
     * 
     * @type {string}
     * @memberof PlayerUpdateInput
     */
    height?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerUpdateInput
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerUpdateInput
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerUpdateInput
     */
    status?: string;
}

/**
 * Check if a given object implements the PlayerUpdateInput interface.
 */
export function instanceOfPlayerUpdateInput(value: object): value is PlayerUpdateInput {
    return true;
}

export function PlayerUpdateInputFromJSON(json: any): PlayerUpdateInput {
    return PlayerUpdateInputFromJSONTyped(json, false);
}

export function PlayerUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'position': json['position'] == null ? undefined : json['position'],
        'schoolType': json['school_type'] == null ? undefined : json['school_type'],
        'school': json['school'] == null ? undefined : json['school'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'graduationYear': json['graduation_year'] == null ? undefined : json['graduation_year'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'height': json['height'] == null ? undefined : json['height'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function PlayerUpdateInputToJSON(json: any): PlayerUpdateInput {
    return PlayerUpdateInputToJSONTyped(json, false);
}

export function PlayerUpdateInputToJSONTyped(value?: PlayerUpdateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'position': value['position'],
        'school_type': value['schoolType'],
        'school': value['school'],
        'city': value['city'],
        'state': value['state'],
        'graduation_year': value['graduationYear'],
        'weight': value['weight'],
        'height': value['height'],
        'email': value['email'],
        'phone': value['phone'],
        'status': value['status'],
    };
}

