/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProspectUpdateInput
 */
export interface ProspectUpdateInput {
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    primaryPosition?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    secondaryPosition?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    schoolType?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    schoolName?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    state?: string;
    /**
     * 
     * @type {number}
     * @memberof ProspectUpdateInput
     */
    graduationYear?: number;
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    classYear?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    bats?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    throws?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    height?: string;
    /**
     * 
     * @type {number}
     * @memberof ProspectUpdateInput
     */
    weight?: number;
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectUpdateInput
     */
    phone?: string;
}

/**
 * Check if a given object implements the ProspectUpdateInput interface.
 */
export function instanceOfProspectUpdateInput(value: object): value is ProspectUpdateInput {
    return true;
}

export function ProspectUpdateInputFromJSON(json: any): ProspectUpdateInput {
    return ProspectUpdateInputFromJSONTyped(json, false);
}

export function ProspectUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProspectUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'primaryPosition': json['primary_position'] == null ? undefined : json['primary_position'],
        'secondaryPosition': json['secondary_position'] == null ? undefined : json['secondary_position'],
        'schoolType': json['school_type'] == null ? undefined : json['school_type'],
        'schoolName': json['school_name'] == null ? undefined : json['school_name'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'graduationYear': json['graduation_year'] == null ? undefined : json['graduation_year'],
        'classYear': json['class_year'] == null ? undefined : json['class_year'],
        'bats': json['bats'] == null ? undefined : json['bats'],
        'throws': json['throws'] == null ? undefined : json['throws'],
        'height': json['height'] == null ? undefined : json['height'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'status': json['status'] == null ? undefined : json['status'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function ProspectUpdateInputToJSON(json: any): ProspectUpdateInput {
    return ProspectUpdateInputToJSONTyped(json, false);
}

export function ProspectUpdateInputToJSONTyped(value?: ProspectUpdateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'primary_position': value['primaryPosition'],
        'secondary_position': value['secondaryPosition'],
        'school_type': value['schoolType'],
        'school_name': value['schoolName'],
        'city': value['city'],
        'state': value['state'],
        'graduation_year': value['graduationYear'],
        'class_year': value['classYear'],
        'bats': value['bats'],
        'throws': value['throws'],
        'height': value['height'],
        'weight': value['weight'],
        'status': value['status'],
        'notes': value['notes'],
        'email': value['email'],
        'phone': value['phone'],
    };
}

