/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProspectCreateInput
 */
export interface ProspectCreateInput {
    /**
     * 
     * @type {string}
     * @memberof ProspectCreateInput
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectCreateInput
     */
    lastName: string;
    /**
     * 
     * @type {ProspectCreateInputPrimaryPositionEnum}
     * @memberof ProspectCreateInput
     */
    primaryPosition: ProspectCreateInputPrimaryPositionEnum;
    /**
     * 
     * @type {ProspectCreateInputSecondaryPositionEnum}
     * @memberof ProspectCreateInput
     */
    secondaryPosition?: ProspectCreateInputSecondaryPositionEnum;
    /**
     * 
     * @type {ProspectCreateInputSchoolTypeEnum}
     * @memberof ProspectCreateInput
     */
    schoolType?: ProspectCreateInputSchoolTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ProspectCreateInput
     */
    schoolName?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectCreateInput
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectCreateInput
     */
    state?: string;
    /**
     * 
     * @type {number}
     * @memberof ProspectCreateInput
     */
    graduationYear?: number;
    /**
     * 
     * @type {ProspectCreateInputClassYearEnum}
     * @memberof ProspectCreateInput
     */
    classYear?: ProspectCreateInputClassYearEnum;
    /**
     * 
     * @type {ProspectCreateInputBatsEnum}
     * @memberof ProspectCreateInput
     */
    bats?: ProspectCreateInputBatsEnum;
    /**
     * 
     * @type {ProspectCreateInputThrowsEnum}
     * @memberof ProspectCreateInput
     */
    throws?: ProspectCreateInputThrowsEnum;
    /**
     * 
     * @type {string}
     * @memberof ProspectCreateInput
     */
    height?: string;
    /**
     * 
     * @type {number}
     * @memberof ProspectCreateInput
     */
    weight?: number;
    /**
     * 
     * @type {number}
     * @memberof ProspectCreateInput
     */
    sixtyYardDash?: number;
    /**
     * 
     * @type {number}
     * @memberof ProspectCreateInput
     */
    fastballVelocity?: number;
    /**
     * 
     * @type {number}
     * @memberof ProspectCreateInput
     */
    exitVelocity?: number;
    /**
     * 
     * @type {number}
     * @memberof ProspectCreateInput
     */
    gpa?: number;
    /**
     * 
     * @type {number}
     * @memberof ProspectCreateInput
     */
    satScore?: number;
    /**
     * 
     * @type {number}
     * @memberof ProspectCreateInput
     */
    actScore?: number;
    /**
     * 
     * @type {ProspectCreateInputStatusEnum}
     * @memberof ProspectCreateInput
     */
    status?: ProspectCreateInputStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ProspectCreateInput
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectCreateInput
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectCreateInput
     */
    phone?: string;
}


/**
 * @export
 */
export const ProspectCreateInputPrimaryPositionEnum = {
    P: 'P',
    C: 'C',
    _1B: '1B',
    _2B: '2B',
    _3B: '3B',
    Ss: 'SS',
    Lf: 'LF',
    Cf: 'CF',
    Rf: 'RF',
    Of: 'OF',
    Dh: 'DH',
    Utl: 'UTL'
} as const;
export type ProspectCreateInputPrimaryPositionEnum = typeof ProspectCreateInputPrimaryPositionEnum[keyof typeof ProspectCreateInputPrimaryPositionEnum];

/**
 * @export
 */
export const ProspectCreateInputSecondaryPositionEnum = {
    P: 'P',
    C: 'C',
    _1B: '1B',
    _2B: '2B',
    _3B: '3B',
    Ss: 'SS',
    Lf: 'LF',
    Cf: 'CF',
    Rf: 'RF',
    Of: 'OF',
    Dh: 'DH',
    Utl: 'UTL'
} as const;
export type ProspectCreateInputSecondaryPositionEnum = typeof ProspectCreateInputSecondaryPositionEnum[keyof typeof ProspectCreateInputSecondaryPositionEnum];

/**
 * @export
 */
export const ProspectCreateInputSchoolTypeEnum = {
    Hs: 'HS',
    Juco: 'JUCO',
    D1: 'D1',
    D2: 'D2',
    D3: 'D3',
    Naia: 'NAIA',
    Independent: 'Independent'
} as const;
export type ProspectCreateInputSchoolTypeEnum = typeof ProspectCreateInputSchoolTypeEnum[keyof typeof ProspectCreateInputSchoolTypeEnum];

/**
 * @export
 */
export const ProspectCreateInputClassYearEnum = {
    Fr: 'FR',
    So: 'SO',
    Jr: 'JR',
    Sr: 'SR',
    Gr: 'GR'
} as const;
export type ProspectCreateInputClassYearEnum = typeof ProspectCreateInputClassYearEnum[keyof typeof ProspectCreateInputClassYearEnum];

/**
 * @export
 */
export const ProspectCreateInputBatsEnum = {
    L: 'L',
    R: 'R',
    S: 'S'
} as const;
export type ProspectCreateInputBatsEnum = typeof ProspectCreateInputBatsEnum[keyof typeof ProspectCreateInputBatsEnum];

/**
 * @export
 */
export const ProspectCreateInputThrowsEnum = {
    L: 'L',
    R: 'R'
} as const;
export type ProspectCreateInputThrowsEnum = typeof ProspectCreateInputThrowsEnum[keyof typeof ProspectCreateInputThrowsEnum];

/**
 * @export
 */
export const ProspectCreateInputStatusEnum = {
    Identified: 'identified',
    Evaluating: 'evaluating',
    Contacted: 'contacted',
    Visiting: 'visiting',
    Offered: 'offered',
    Committed: 'committed',
    Signed: 'signed',
    Passed: 'passed'
} as const;
export type ProspectCreateInputStatusEnum = typeof ProspectCreateInputStatusEnum[keyof typeof ProspectCreateInputStatusEnum];


/**
 * Check if a given object implements the ProspectCreateInput interface.
 */
export function instanceOfProspectCreateInput(value: object): value is ProspectCreateInput {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('primaryPosition' in value) || value['primaryPosition'] === undefined) return false;
    return true;
}

export function ProspectCreateInputFromJSON(json: any): ProspectCreateInput {
    return ProspectCreateInputFromJSONTyped(json, false);
}

export function ProspectCreateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProspectCreateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'primaryPosition': json['primary_position'],
        'secondaryPosition': json['secondary_position'] == null ? undefined : json['secondary_position'],
        'schoolType': json['school_type'] == null ? undefined : json['school_type'],
        'schoolName': json['school_name'] == null ? undefined : json['school_name'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'graduationYear': json['graduation_year'] == null ? undefined : json['graduation_year'],
        'classYear': json['class_year'] == null ? undefined : json['class_year'],
        'bats': json['bats'] == null ? undefined : json['bats'],
        'throws': json['throws'] == null ? undefined : json['throws'],
        'height': json['height'] == null ? undefined : json['height'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'sixtyYardDash': json['sixty_yard_dash'] == null ? undefined : json['sixty_yard_dash'],
        'fastballVelocity': json['fastball_velocity'] == null ? undefined : json['fastball_velocity'],
        'exitVelocity': json['exit_velocity'] == null ? undefined : json['exit_velocity'],
        'gpa': json['gpa'] == null ? undefined : json['gpa'],
        'satScore': json['sat_score'] == null ? undefined : json['sat_score'],
        'actScore': json['act_score'] == null ? undefined : json['act_score'],
        'status': json['status'] == null ? undefined : json['status'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function ProspectCreateInputToJSON(json: any): ProspectCreateInput {
    return ProspectCreateInputToJSONTyped(json, false);
}

export function ProspectCreateInputToJSONTyped(value?: ProspectCreateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'primary_position': value['primaryPosition'],
        'secondary_position': value['secondaryPosition'],
        'school_type': value['schoolType'],
        'school_name': value['schoolName'],
        'city': value['city'],
        'state': value['state'],
        'graduation_year': value['graduationYear'],
        'class_year': value['classYear'],
        'bats': value['bats'],
        'throws': value['throws'],
        'height': value['height'],
        'weight': value['weight'],
        'sixty_yard_dash': value['sixtyYardDash'],
        'fastball_velocity': value['fastballVelocity'],
        'exit_velocity': value['exitVelocity'],
        'gpa': value['gpa'],
        'sat_score': value['satScore'],
        'act_score': value['actScore'],
        'status': value['status'],
        'notes': value['notes'],
        'email': value['email'],
        'phone': value['phone'],
    };
}

