/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Someone you're recruiting (vs Player on roster). See docs/api/scouting-system-api.md
 * @export
 * @interface Prospect
 */
export interface Prospect {
    /**
     * 
     * @type {number}
     * @memberof Prospect
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Prospect
     */
    teamId?: number;
    /**
     * 
     * @type {number}
     * @memberof Prospect
     */
    createdBy?: number;
    /**
     * 
     * @type {string}
     * @memberof Prospect
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof Prospect
     */
    lastName?: string;
    /**
     * 
     * @type {ProspectPrimaryPositionEnum}
     * @memberof Prospect
     */
    primaryPosition?: ProspectPrimaryPositionEnum;
    /**
     * 
     * @type {string}
     * @memberof Prospect
     */
    secondaryPosition?: string;
    /**
     * 
     * @type {ProspectSchoolTypeEnum}
     * @memberof Prospect
     */
    schoolType?: ProspectSchoolTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Prospect
     */
    schoolName?: string;
    /**
     * 
     * @type {string}
     * @memberof Prospect
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof Prospect
     */
    state?: string;
    /**
     * 
     * @type {number}
     * @memberof Prospect
     */
    graduationYear?: number;
    /**
     * 
     * @type {ProspectClassYearEnum}
     * @memberof Prospect
     */
    classYear?: ProspectClassYearEnum;
    /**
     * 
     * @type {ProspectBatsEnum}
     * @memberof Prospect
     */
    bats?: ProspectBatsEnum;
    /**
     * 
     * @type {ProspectThrowsEnum}
     * @memberof Prospect
     */
    throws?: ProspectThrowsEnum;
    /**
     * 
     * @type {ProspectStatusEnum}
     * @memberof Prospect
     */
    status?: ProspectStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Prospect
     */
    notes?: string;
    /**
     * 
     * @type {Date}
     * @memberof Prospect
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Prospect
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const ProspectPrimaryPositionEnum = {
    P: 'P',
    C: 'C',
    _1B: '1B',
    _2B: '2B',
    _3B: '3B',
    Ss: 'SS',
    Lf: 'LF',
    Cf: 'CF',
    Rf: 'RF',
    Of: 'OF',
    Dh: 'DH',
    Utl: 'UTL'
} as const;
export type ProspectPrimaryPositionEnum = typeof ProspectPrimaryPositionEnum[keyof typeof ProspectPrimaryPositionEnum];

/**
 * @export
 */
export const ProspectSchoolTypeEnum = {
    Hs: 'HS',
    Juco: 'JUCO',
    D1: 'D1',
    D2: 'D2',
    D3: 'D3',
    Naia: 'NAIA',
    Independent: 'Independent'
} as const;
export type ProspectSchoolTypeEnum = typeof ProspectSchoolTypeEnum[keyof typeof ProspectSchoolTypeEnum];

/**
 * @export
 */
export const ProspectClassYearEnum = {
    Fr: 'FR',
    So: 'SO',
    Jr: 'JR',
    Sr: 'SR',
    Gr: 'GR'
} as const;
export type ProspectClassYearEnum = typeof ProspectClassYearEnum[keyof typeof ProspectClassYearEnum];

/**
 * @export
 */
export const ProspectBatsEnum = {
    L: 'L',
    R: 'R',
    S: 'S'
} as const;
export type ProspectBatsEnum = typeof ProspectBatsEnum[keyof typeof ProspectBatsEnum];

/**
 * @export
 */
export const ProspectThrowsEnum = {
    L: 'L',
    R: 'R'
} as const;
export type ProspectThrowsEnum = typeof ProspectThrowsEnum[keyof typeof ProspectThrowsEnum];

/**
 * @export
 */
export const ProspectStatusEnum = {
    Identified: 'identified',
    Evaluating: 'evaluating',
    Contacted: 'contacted',
    Visiting: 'visiting',
    Offered: 'offered',
    Committed: 'committed',
    Signed: 'signed',
    Passed: 'passed'
} as const;
export type ProspectStatusEnum = typeof ProspectStatusEnum[keyof typeof ProspectStatusEnum];


/**
 * Check if a given object implements the Prospect interface.
 */
export function instanceOfProspect(value: object): value is Prospect {
    return true;
}

export function ProspectFromJSON(json: any): Prospect {
    return ProspectFromJSONTyped(json, false);
}

export function ProspectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Prospect {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'teamId': json['team_id'] == null ? undefined : json['team_id'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'primaryPosition': json['primary_position'] == null ? undefined : json['primary_position'],
        'secondaryPosition': json['secondary_position'] == null ? undefined : json['secondary_position'],
        'schoolType': json['school_type'] == null ? undefined : json['school_type'],
        'schoolName': json['school_name'] == null ? undefined : json['school_name'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'graduationYear': json['graduation_year'] == null ? undefined : json['graduation_year'],
        'classYear': json['class_year'] == null ? undefined : json['class_year'],
        'bats': json['bats'] == null ? undefined : json['bats'],
        'throws': json['throws'] == null ? undefined : json['throws'],
        'status': json['status'] == null ? undefined : json['status'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function ProspectToJSON(json: any): Prospect {
    return ProspectToJSONTyped(json, false);
}

export function ProspectToJSONTyped(value?: Prospect | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'team_id': value['teamId'],
        'created_by': value['createdBy'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'primary_position': value['primaryPosition'],
        'secondary_position': value['secondaryPosition'],
        'school_type': value['schoolType'],
        'school_name': value['schoolName'],
        'city': value['city'],
        'state': value['state'],
        'graduation_year': value['graduationYear'],
        'class_year': value['classYear'],
        'bats': value['bats'],
        'throws': value['throws'],
        'status': value['status'],
        'notes': value['notes'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

