/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Grades can be numeric (20-80) or letter (B+, A, etc). Event types: game, showcase, practice, workout, video.
 * Present/future grade pairs for each skill. See docs/api/scouting-system-api.md.
 * 
 * @export
 * @interface ScoutingReportProspectInput
 */
export interface ScoutingReportProspectInput {
    /**
     * 
     * @type {Date}
     * @memberof ScoutingReportProspectInput
     */
    reportDate?: Date;
    /**
     * 
     * @type {ScoutingReportProspectInputEventTypeEnum}
     * @memberof ScoutingReportProspectInput
     */
    eventType?: ScoutingReportProspectInputEventTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof ScoutingReportProspectInput
     */
    overallPresent?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ScoutingReportProspectInput
     */
    overallFuture?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ScoutingReportProspectInput
     */
    hittingPresent?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ScoutingReportProspectInput
     */
    hittingFuture?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ScoutingReportProspectInput
     */
    pitchingPresent?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ScoutingReportProspectInput
     */
    pitchingFuture?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ScoutingReportProspectInput
     */
    fieldingPresent?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ScoutingReportProspectInput
     */
    fieldingFuture?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ScoutingReportProspectInput
     */
    speedPresent?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ScoutingReportProspectInput
     */
    speedFuture?: any | null;
    /**
     * 
     * @type {number}
     * @memberof ScoutingReportProspectInput
     */
    sixtyYardDash?: number;
    /**
     * 
     * @type {string}
     * @memberof ScoutingReportProspectInput
     */
    mlbComparison?: string;
    /**
     * 
     * @type {string}
     * @memberof ScoutingReportProspectInput
     */
    notes?: string;
}


/**
 * @export
 */
export const ScoutingReportProspectInputEventTypeEnum = {
    Game: 'game',
    Showcase: 'showcase',
    Practice: 'practice',
    Workout: 'workout',
    Video: 'video'
} as const;
export type ScoutingReportProspectInputEventTypeEnum = typeof ScoutingReportProspectInputEventTypeEnum[keyof typeof ScoutingReportProspectInputEventTypeEnum];


/**
 * Check if a given object implements the ScoutingReportProspectInput interface.
 */
export function instanceOfScoutingReportProspectInput(value: object): value is ScoutingReportProspectInput {
    return true;
}

export function ScoutingReportProspectInputFromJSON(json: any): ScoutingReportProspectInput {
    return ScoutingReportProspectInputFromJSONTyped(json, false);
}

export function ScoutingReportProspectInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoutingReportProspectInput {
    if (json == null) {
        return json;
    }
    return {
        
        'reportDate': json['report_date'] == null ? undefined : (new Date(json['report_date'])),
        'eventType': json['event_type'] == null ? undefined : json['event_type'],
        'overallPresent': json['overall_present'] == null ? undefined : json['overall_present'],
        'overallFuture': json['overall_future'] == null ? undefined : json['overall_future'],
        'hittingPresent': json['hitting_present'] == null ? undefined : json['hitting_present'],
        'hittingFuture': json['hitting_future'] == null ? undefined : json['hitting_future'],
        'pitchingPresent': json['pitching_present'] == null ? undefined : json['pitching_present'],
        'pitchingFuture': json['pitching_future'] == null ? undefined : json['pitching_future'],
        'fieldingPresent': json['fielding_present'] == null ? undefined : json['fielding_present'],
        'fieldingFuture': json['fielding_future'] == null ? undefined : json['fielding_future'],
        'speedPresent': json['speed_present'] == null ? undefined : json['speed_present'],
        'speedFuture': json['speed_future'] == null ? undefined : json['speed_future'],
        'sixtyYardDash': json['sixty_yard_dash'] == null ? undefined : json['sixty_yard_dash'],
        'mlbComparison': json['mlb_comparison'] == null ? undefined : json['mlb_comparison'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function ScoutingReportProspectInputToJSON(json: any): ScoutingReportProspectInput {
    return ScoutingReportProspectInputToJSONTyped(json, false);
}

export function ScoutingReportProspectInputToJSONTyped(value?: ScoutingReportProspectInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'report_date': value['reportDate'] == null ? value['reportDate'] : value['reportDate'].toISOString().substring(0,10),
        'event_type': value['eventType'],
        'overall_present': value['overallPresent'],
        'overall_future': value['overallFuture'],
        'hitting_present': value['hittingPresent'],
        'hitting_future': value['hittingFuture'],
        'pitching_present': value['pitchingPresent'],
        'pitching_future': value['pitchingFuture'],
        'fielding_present': value['fieldingPresent'],
        'fielding_future': value['fieldingFuture'],
        'speed_present': value['speedPresent'],
        'speed_future': value['speedFuture'],
        'sixty_yard_dash': value['sixtyYardDash'],
        'mlb_comparison': value['mlbComparison'],
        'notes': value['notes'],
    };
}

