/* tslint:disable */
/* eslint-disable */
/**
 * Sports2 API
 * REST API for the Sports2 collegiate baseball scouting and team management platform.  ## Authentication All endpoints (except public ones) require: - `Authorization: Bearer <JWT>` header - `x-csrf-token` header on state-changing requests (POST, PUT, PATCH, DELETE)  Get a CSRF token first: `GET /api/v1/auth/csrf-token`  ## Response Format Success: `{ \"success\": true, \"data\": {...} }` Error: `{ \"success\": false, \"error\": \"...\" }`  ## Scouting System See `docs/api/scouting-system-api.md` for the scouting system redesign including Prospects, 20-80 grading scale, present/future grades, and recruiting pipeline. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScoutingReportUpdateInput
 */
export interface ScoutingReportUpdateInput {
    /**
     * 
     * @type {Date}
     * @memberof ScoutingReportUpdateInput
     */
    reportDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ScoutingReportUpdateInput
     */
    eventType?: string;
    /**
     * 
     * @type {any}
     * @memberof ScoutingReportUpdateInput
     */
    overallPresent?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ScoutingReportUpdateInput
     */
    overallFuture?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ScoutingReportUpdateInput
     */
    notes?: string;
}

/**
 * Check if a given object implements the ScoutingReportUpdateInput interface.
 */
export function instanceOfScoutingReportUpdateInput(value: object): value is ScoutingReportUpdateInput {
    return true;
}

export function ScoutingReportUpdateInputFromJSON(json: any): ScoutingReportUpdateInput {
    return ScoutingReportUpdateInputFromJSONTyped(json, false);
}

export function ScoutingReportUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoutingReportUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'reportDate': json['report_date'] == null ? undefined : (new Date(json['report_date'])),
        'eventType': json['event_type'] == null ? undefined : json['event_type'],
        'overallPresent': json['overall_present'] == null ? undefined : json['overall_present'],
        'overallFuture': json['overall_future'] == null ? undefined : json['overall_future'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function ScoutingReportUpdateInputToJSON(json: any): ScoutingReportUpdateInput {
    return ScoutingReportUpdateInputToJSONTyped(json, false);
}

export function ScoutingReportUpdateInputToJSONTyped(value?: ScoutingReportUpdateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'report_date': value['reportDate'] == null ? value['reportDate'] : value['reportDate'].toISOString().substring(0,10),
        'event_type': value['eventType'],
        'overall_present': value['overallPresent'],
        'overall_future': value['overallFuture'],
        'notes': value['notes'],
    };
}

