/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedVendorsIndexRouteImport } from './routes/_authenticated/vendors/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTeamSettingsIndexRouteImport } from './routes/_authenticated/team-settings/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedScoutsIndexRouteImport } from './routes/_authenticated/scouts/index'
import { Route as AuthenticatedScoutingIndexRouteImport } from './routes/_authenticated/scouting/index'
import { Route as AuthenticatedSchedulesIndexRouteImport } from './routes/_authenticated/schedules/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedRecruitingIndexRouteImport } from './routes/_authenticated/recruiting/index'
import { Route as AuthenticatedProspectsIndexRouteImport } from './routes/_authenticated/prospects/index'
import { Route as AuthenticatedPreferenceListsIndexRouteImport } from './routes/_authenticated/preference-lists/index'
import { Route as AuthenticatedPlayersIndexRouteImport } from './routes/_authenticated/players/index'
import { Route as AuthenticatedIntegrationsIndexRouteImport } from './routes/_authenticated/integrations/index'
import { Route as AuthenticatedHighSchoolCoachesIndexRouteImport } from './routes/_authenticated/high-school-coaches/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedGamesIndexRouteImport } from './routes/_authenticated/games/index'
import { Route as AuthenticatedDepthChartsIndexRouteImport } from './routes/_authenticated/depth-charts/index'
import { Route as AuthenticatedCoachesIndexRouteImport } from './routes/_authenticated/coaches/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedScoutingCreateRouteImport } from './routes/_authenticated/scouting/create'
import { Route as AuthenticatedScoutingIdRouteImport } from './routes/_authenticated/scouting/$id'
import { Route as AuthenticatedReportsAnalyticsRouteImport } from './routes/_authenticated/reports/analytics'
import { Route as AuthenticatedProspectsCreateRouteImport } from './routes/_authenticated/prospects/create'
import { Route as AuthenticatedProspectsIdRouteImport } from './routes/_authenticated/prospects/$id'
import { Route as AuthenticatedPlayersCreateRouteImport } from './routes/_authenticated/players/create'
import { Route as AuthenticatedPlayersIdRouteImport } from './routes/_authenticated/players/$id'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDepthChartsIdRouteImport } from './routes/_authenticated/depth-charts/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorsIndexRoute =
  AuthenticatedVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamSettingsIndexRoute =
  AuthenticatedTeamSettingsIndexRouteImport.update({
    id: '/team-settings/',
    path: '/team-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedScoutsIndexRoute =
  AuthenticatedScoutsIndexRouteImport.update({
    id: '/scouts/',
    path: '/scouts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScoutingIndexRoute =
  AuthenticatedScoutingIndexRouteImport.update({
    id: '/scouting/',
    path: '/scouting/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedulesIndexRoute =
  AuthenticatedSchedulesIndexRouteImport.update({
    id: '/schedules/',
    path: '/schedules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruitingIndexRoute =
  AuthenticatedRecruitingIndexRouteImport.update({
    id: '/recruiting/',
    path: '/recruiting/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProspectsIndexRoute =
  AuthenticatedProspectsIndexRouteImport.update({
    id: '/prospects/',
    path: '/prospects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPreferenceListsIndexRoute =
  AuthenticatedPreferenceListsIndexRouteImport.update({
    id: '/preference-lists/',
    path: '/preference-lists/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayersIndexRoute =
  AuthenticatedPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrationsIndexRoute =
  AuthenticatedIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHighSchoolCoachesIndexRoute =
  AuthenticatedHighSchoolCoachesIndexRouteImport.update({
    id: '/high-school-coaches/',
    path: '/high-school-coaches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGamesIndexRoute = AuthenticatedGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepthChartsIndexRoute =
  AuthenticatedDepthChartsIndexRouteImport.update({
    id: '/depth-charts/',
    path: '/depth-charts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoachesIndexRoute =
  AuthenticatedCoachesIndexRouteImport.update({
    id: '/coaches/',
    path: '/coaches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedScoutingCreateRoute =
  AuthenticatedScoutingCreateRouteImport.update({
    id: '/scouting/create',
    path: '/scouting/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScoutingIdRoute = AuthenticatedScoutingIdRouteImport.update({
  id: '/scouting/$id',
  path: '/scouting/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsAnalyticsRoute =
  AuthenticatedReportsAnalyticsRouteImport.update({
    id: '/reports/analytics',
    path: '/reports/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProspectsCreateRoute =
  AuthenticatedProspectsCreateRouteImport.update({
    id: '/prospects/create',
    path: '/prospects/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProspectsIdRoute =
  AuthenticatedProspectsIdRouteImport.update({
    id: '/prospects/$id',
    path: '/prospects/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayersCreateRoute =
  AuthenticatedPlayersCreateRouteImport.update({
    id: '/players/create',
    path: '/players/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayersIdRoute = AuthenticatedPlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepthChartsIdRoute =
  AuthenticatedDepthChartsIdRouteImport.update({
    id: '/depth-charts/$id',
    path: '/depth-charts/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/register': typeof authRegisterRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/depth-charts/$id': typeof AuthenticatedDepthChartsIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/players/$id': typeof AuthenticatedPlayersIdRoute
  '/players/create': typeof AuthenticatedPlayersCreateRoute
  '/prospects/$id': typeof AuthenticatedProspectsIdRoute
  '/prospects/create': typeof AuthenticatedProspectsCreateRoute
  '/reports/analytics': typeof AuthenticatedReportsAnalyticsRoute
  '/scouting/$id': typeof AuthenticatedScoutingIdRoute
  '/scouting/create': typeof AuthenticatedScoutingCreateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/coaches/': typeof AuthenticatedCoachesIndexRoute
  '/depth-charts/': typeof AuthenticatedDepthChartsIndexRoute
  '/games/': typeof AuthenticatedGamesIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/high-school-coaches/': typeof AuthenticatedHighSchoolCoachesIndexRoute
  '/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/players/': typeof AuthenticatedPlayersIndexRoute
  '/preference-lists/': typeof AuthenticatedPreferenceListsIndexRoute
  '/prospects/': typeof AuthenticatedProspectsIndexRoute
  '/recruiting/': typeof AuthenticatedRecruitingIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/schedules/': typeof AuthenticatedSchedulesIndexRoute
  '/scouting/': typeof AuthenticatedScoutingIndexRoute
  '/scouts/': typeof AuthenticatedScoutsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/team-settings/': typeof AuthenticatedTeamSettingsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/vendors/': typeof AuthenticatedVendorsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/register': typeof authRegisterRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/': typeof AuthenticatedIndexRoute
  '/depth-charts/$id': typeof AuthenticatedDepthChartsIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/players/$id': typeof AuthenticatedPlayersIdRoute
  '/players/create': typeof AuthenticatedPlayersCreateRoute
  '/prospects/$id': typeof AuthenticatedProspectsIdRoute
  '/prospects/create': typeof AuthenticatedProspectsCreateRoute
  '/reports/analytics': typeof AuthenticatedReportsAnalyticsRoute
  '/scouting/$id': typeof AuthenticatedScoutingIdRoute
  '/scouting/create': typeof AuthenticatedScoutingCreateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/coaches': typeof AuthenticatedCoachesIndexRoute
  '/depth-charts': typeof AuthenticatedDepthChartsIndexRoute
  '/games': typeof AuthenticatedGamesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/high-school-coaches': typeof AuthenticatedHighSchoolCoachesIndexRoute
  '/integrations': typeof AuthenticatedIntegrationsIndexRoute
  '/players': typeof AuthenticatedPlayersIndexRoute
  '/preference-lists': typeof AuthenticatedPreferenceListsIndexRoute
  '/prospects': typeof AuthenticatedProspectsIndexRoute
  '/recruiting': typeof AuthenticatedRecruitingIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/schedules': typeof AuthenticatedSchedulesIndexRoute
  '/scouting': typeof AuthenticatedScoutingIndexRoute
  '/scouts': typeof AuthenticatedScoutsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/team-settings': typeof AuthenticatedTeamSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/depth-charts/$id': typeof AuthenticatedDepthChartsIdRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/players/$id': typeof AuthenticatedPlayersIdRoute
  '/_authenticated/players/create': typeof AuthenticatedPlayersCreateRoute
  '/_authenticated/prospects/$id': typeof AuthenticatedProspectsIdRoute
  '/_authenticated/prospects/create': typeof AuthenticatedProspectsCreateRoute
  '/_authenticated/reports/analytics': typeof AuthenticatedReportsAnalyticsRoute
  '/_authenticated/scouting/$id': typeof AuthenticatedScoutingIdRoute
  '/_authenticated/scouting/create': typeof AuthenticatedScoutingCreateRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/coaches/': typeof AuthenticatedCoachesIndexRoute
  '/_authenticated/depth-charts/': typeof AuthenticatedDepthChartsIndexRoute
  '/_authenticated/games/': typeof AuthenticatedGamesIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/high-school-coaches/': typeof AuthenticatedHighSchoolCoachesIndexRoute
  '/_authenticated/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/_authenticated/players/': typeof AuthenticatedPlayersIndexRoute
  '/_authenticated/preference-lists/': typeof AuthenticatedPreferenceListsIndexRoute
  '/_authenticated/prospects/': typeof AuthenticatedProspectsIndexRoute
  '/_authenticated/recruiting/': typeof AuthenticatedRecruitingIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/schedules/': typeof AuthenticatedSchedulesIndexRoute
  '/_authenticated/scouting/': typeof AuthenticatedScoutingIndexRoute
  '/_authenticated/scouts/': typeof AuthenticatedScoutsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/team-settings/': typeof AuthenticatedTeamSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/vendors/': typeof AuthenticatedVendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/register'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/depth-charts/$id'
    | '/errors/$error'
    | '/players/$id'
    | '/players/create'
    | '/prospects/$id'
    | '/prospects/create'
    | '/reports/analytics'
    | '/scouting/$id'
    | '/scouting/create'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps/'
    | '/chats/'
    | '/coaches/'
    | '/depth-charts/'
    | '/games/'
    | '/help-center/'
    | '/high-school-coaches/'
    | '/integrations/'
    | '/players/'
    | '/preference-lists/'
    | '/prospects/'
    | '/recruiting/'
    | '/reports/'
    | '/schedules/'
    | '/scouting/'
    | '/scouts/'
    | '/settings/'
    | '/tasks/'
    | '/team-settings/'
    | '/users/'
    | '/vendors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/register'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/'
    | '/depth-charts/$id'
    | '/errors/$error'
    | '/players/$id'
    | '/players/create'
    | '/prospects/$id'
    | '/prospects/create'
    | '/reports/analytics'
    | '/scouting/$id'
    | '/scouting/create'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/chats'
    | '/coaches'
    | '/depth-charts'
    | '/games'
    | '/help-center'
    | '/high-school-coaches'
    | '/integrations'
    | '/players'
    | '/preference-lists'
    | '/prospects'
    | '/recruiting'
    | '/reports'
    | '/schedules'
    | '/scouting'
    | '/scouts'
    | '/settings'
    | '/tasks'
    | '/team-settings'
    | '/users'
    | '/vendors'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/otp'
    | '/(auth)/register'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/dashboard'
    | '/_authenticated/'
    | '/_authenticated/depth-charts/$id'
    | '/_authenticated/errors/$error'
    | '/_authenticated/players/$id'
    | '/_authenticated/players/create'
    | '/_authenticated/prospects/$id'
    | '/_authenticated/prospects/create'
    | '/_authenticated/reports/analytics'
    | '/_authenticated/scouting/$id'
    | '/_authenticated/scouting/create'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/coaches/'
    | '/_authenticated/depth-charts/'
    | '/_authenticated/games/'
    | '/_authenticated/help-center/'
    | '/_authenticated/high-school-coaches/'
    | '/_authenticated/integrations/'
    | '/_authenticated/players/'
    | '/_authenticated/preference-lists/'
    | '/_authenticated/prospects/'
    | '/_authenticated/recruiting/'
    | '/_authenticated/reports/'
    | '/_authenticated/schedules/'
    | '/_authenticated/scouting/'
    | '/_authenticated/scouts/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/team-settings/'
    | '/_authenticated/users/'
    | '/_authenticated/vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authOtpRoute: typeof authOtpRoute
  authRegisterRoute: typeof authRegisterRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/': {
      id: '/_authenticated/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AuthenticatedVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-settings/': {
      id: '/_authenticated/team-settings/'
      path: '/team-settings'
      fullPath: '/team-settings/'
      preLoaderRoute: typeof AuthenticatedTeamSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/scouts/': {
      id: '/_authenticated/scouts/'
      path: '/scouts'
      fullPath: '/scouts/'
      preLoaderRoute: typeof AuthenticatedScoutsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scouting/': {
      id: '/_authenticated/scouting/'
      path: '/scouting'
      fullPath: '/scouting/'
      preLoaderRoute: typeof AuthenticatedScoutingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules/': {
      id: '/_authenticated/schedules/'
      path: '/schedules'
      fullPath: '/schedules/'
      preLoaderRoute: typeof AuthenticatedSchedulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiting/': {
      id: '/_authenticated/recruiting/'
      path: '/recruiting'
      fullPath: '/recruiting/'
      preLoaderRoute: typeof AuthenticatedRecruitingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prospects/': {
      id: '/_authenticated/prospects/'
      path: '/prospects'
      fullPath: '/prospects/'
      preLoaderRoute: typeof AuthenticatedProspectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preference-lists/': {
      id: '/_authenticated/preference-lists/'
      path: '/preference-lists'
      fullPath: '/preference-lists/'
      preLoaderRoute: typeof AuthenticatedPreferenceListsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players/': {
      id: '/_authenticated/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof AuthenticatedPlayersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations/': {
      id: '/_authenticated/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AuthenticatedIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/high-school-coaches/': {
      id: '/_authenticated/high-school-coaches/'
      path: '/high-school-coaches'
      fullPath: '/high-school-coaches/'
      preLoaderRoute: typeof AuthenticatedHighSchoolCoachesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/': {
      id: '/_authenticated/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AuthenticatedGamesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depth-charts/': {
      id: '/_authenticated/depth-charts/'
      path: '/depth-charts'
      fullPath: '/depth-charts/'
      preLoaderRoute: typeof AuthenticatedDepthChartsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coaches/': {
      id: '/_authenticated/coaches/'
      path: '/coaches'
      fullPath: '/coaches/'
      preLoaderRoute: typeof AuthenticatedCoachesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/scouting/create': {
      id: '/_authenticated/scouting/create'
      path: '/scouting/create'
      fullPath: '/scouting/create'
      preLoaderRoute: typeof AuthenticatedScoutingCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scouting/$id': {
      id: '/_authenticated/scouting/$id'
      path: '/scouting/$id'
      fullPath: '/scouting/$id'
      preLoaderRoute: typeof AuthenticatedScoutingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/analytics': {
      id: '/_authenticated/reports/analytics'
      path: '/reports/analytics'
      fullPath: '/reports/analytics'
      preLoaderRoute: typeof AuthenticatedReportsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prospects/create': {
      id: '/_authenticated/prospects/create'
      path: '/prospects/create'
      fullPath: '/prospects/create'
      preLoaderRoute: typeof AuthenticatedProspectsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prospects/$id': {
      id: '/_authenticated/prospects/$id'
      path: '/prospects/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof AuthenticatedProspectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players/create': {
      id: '/_authenticated/players/create'
      path: '/players/create'
      fullPath: '/players/create'
      preLoaderRoute: typeof AuthenticatedPlayersCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players/$id': {
      id: '/_authenticated/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof AuthenticatedPlayersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depth-charts/$id': {
      id: '/_authenticated/depth-charts/$id'
      path: '/depth-charts/$id'
      fullPath: '/depth-charts/$id'
      preLoaderRoute: typeof AuthenticatedDepthChartsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDepthChartsIdRoute: typeof AuthenticatedDepthChartsIdRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedPlayersIdRoute: typeof AuthenticatedPlayersIdRoute
  AuthenticatedPlayersCreateRoute: typeof AuthenticatedPlayersCreateRoute
  AuthenticatedProspectsIdRoute: typeof AuthenticatedProspectsIdRoute
  AuthenticatedProspectsCreateRoute: typeof AuthenticatedProspectsCreateRoute
  AuthenticatedReportsAnalyticsRoute: typeof AuthenticatedReportsAnalyticsRoute
  AuthenticatedScoutingIdRoute: typeof AuthenticatedScoutingIdRoute
  AuthenticatedScoutingCreateRoute: typeof AuthenticatedScoutingCreateRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCoachesIndexRoute: typeof AuthenticatedCoachesIndexRoute
  AuthenticatedDepthChartsIndexRoute: typeof AuthenticatedDepthChartsIndexRoute
  AuthenticatedGamesIndexRoute: typeof AuthenticatedGamesIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedHighSchoolCoachesIndexRoute: typeof AuthenticatedHighSchoolCoachesIndexRoute
  AuthenticatedIntegrationsIndexRoute: typeof AuthenticatedIntegrationsIndexRoute
  AuthenticatedPlayersIndexRoute: typeof AuthenticatedPlayersIndexRoute
  AuthenticatedPreferenceListsIndexRoute: typeof AuthenticatedPreferenceListsIndexRoute
  AuthenticatedProspectsIndexRoute: typeof AuthenticatedProspectsIndexRoute
  AuthenticatedRecruitingIndexRoute: typeof AuthenticatedRecruitingIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSchedulesIndexRoute: typeof AuthenticatedSchedulesIndexRoute
  AuthenticatedScoutingIndexRoute: typeof AuthenticatedScoutingIndexRoute
  AuthenticatedScoutsIndexRoute: typeof AuthenticatedScoutsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTeamSettingsIndexRoute: typeof AuthenticatedTeamSettingsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedVendorsIndexRoute: typeof AuthenticatedVendorsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDepthChartsIdRoute: AuthenticatedDepthChartsIdRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedPlayersIdRoute: AuthenticatedPlayersIdRoute,
  AuthenticatedPlayersCreateRoute: AuthenticatedPlayersCreateRoute,
  AuthenticatedProspectsIdRoute: AuthenticatedProspectsIdRoute,
  AuthenticatedProspectsCreateRoute: AuthenticatedProspectsCreateRoute,
  AuthenticatedReportsAnalyticsRoute: AuthenticatedReportsAnalyticsRoute,
  AuthenticatedScoutingIdRoute: AuthenticatedScoutingIdRoute,
  AuthenticatedScoutingCreateRoute: AuthenticatedScoutingCreateRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCoachesIndexRoute: AuthenticatedCoachesIndexRoute,
  AuthenticatedDepthChartsIndexRoute: AuthenticatedDepthChartsIndexRoute,
  AuthenticatedGamesIndexRoute: AuthenticatedGamesIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedHighSchoolCoachesIndexRoute:
    AuthenticatedHighSchoolCoachesIndexRoute,
  AuthenticatedIntegrationsIndexRoute: AuthenticatedIntegrationsIndexRoute,
  AuthenticatedPlayersIndexRoute: AuthenticatedPlayersIndexRoute,
  AuthenticatedPreferenceListsIndexRoute:
    AuthenticatedPreferenceListsIndexRoute,
  AuthenticatedProspectsIndexRoute: AuthenticatedProspectsIndexRoute,
  AuthenticatedRecruitingIndexRoute: AuthenticatedRecruitingIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSchedulesIndexRoute: AuthenticatedSchedulesIndexRoute,
  AuthenticatedScoutingIndexRoute: AuthenticatedScoutingIndexRoute,
  AuthenticatedScoutsIndexRoute: AuthenticatedScoutsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTeamSettingsIndexRoute: AuthenticatedTeamSettingsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedVendorsIndexRoute: AuthenticatedVendorsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authOtpRoute: authOtpRoute,
  authRegisterRoute: authRegisterRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
